### ISSUE TITLE
Unusual formula for measuring the fee rate mismatch

### ISSUE THREAD

**Issue by canndrew** [ACINQ/eclair#1438] opened 2020-05-27 06:44 UTC
The formula eclair uses for calculating the difference between two fee rates is:

```scala
  /**
   * @param referenceFeePerKw reference fee rate per kiloweight
   * @param currentFeePerKw   current fee rate per kiloweight
   * @return the "normalized" difference between i.e local and remote fee rate: |reference - current| / avg(current, reference)
   */
  def feeRateMismatch(referenceFeePerKw: Long, currentFeePerKw: Long): Double =
    Math.abs((2.0 * (referenceFeePerKw - currentFeePerKw)) / (currentFeePerKw + referenceFeePerKw))
```

This seems a bit odd to me. If the reference fee rate is 1btc and the current fee rate is 0.0001btc then the average of the two will be (approximately) 0.5btc - which is half the reference fee rate but 5000 times the current fee rate. It would make more sense to measure this on a log scale so that an infinite difference (in terms of orders-of-magnitude) becomes an infinite `feeRateMismatch`, rather than a `feeRateMismatch` of 2.

Is it worth changing the formula to `|log(reference) - log(current)|`? (And also changing the name of the config option to avoid silently changing its meaning?)

**Comment by t-bast** [comment] 2020-06-03 10:05
Can you explain why you would want to change that? What problem would that solve?
Don't forget that the mismatch threshold is configurable in `eclair.conf`, we want users to be able to put a (somewhat) simple double value there to choose their tolerance to mismatches (https://github.com/ACINQ/eclair/blob/c04a4cef2ab143fdf232225576dd01554c1c42ca/eclair-core/src/main/resources/reference.conf#L100).

**Comment by viaj3ro** [comment] 2020-06-19 14:57
the 1.56 (8x) value caused a lot of channel failures for me. I'm using 5.56 now. This works but it's unclear to what multiple that actually means

the config could be more clear and should probably use a default value that doesn't cause a bunch of channels to be force closed every time there is a significant on-chain fee spike.

**Comment by t-bast** [comment] 2020-06-19 15:44
> should probably use a default value that doesn't cause a bunch of channels to be force closed every time there is a significant on-chain fee spike

The issue is that *this is an intractable problem*. There is no good solution for now.
We are trying to predict the future and trying to predict how others predict the future.
This is simply something that cannot work 100% of the time, hence channels sometimes closing.
The trade-off is potentially losing funds if we don't close these channels, so I think this is a fair trade-off.

There is a silver lining though: once channels use [anchor outputs](https://gist.github.com/t-bast/22320336e0816ca5578fdca4ad824d12#anchor-outputs), we can be way more tolerant to feerate mismatch because we'll be able to bump fees when/if the channel closes. But for now we're stuck with this imperfection.

**Closed** 2020-07-01 12:45 UTC
