### ISSUE TITLE
[mobile] Receive lightning payment / create payment request

### ISSUE THREAD

**Issue by xorq** [ACINQ/eclair#540] opened 2018-04-04 22:59 UTC
Is there a way to receive lightning payments / create payment requests with the mobile version ?
Can't find a way and this is terribly missing... 
HAVE to make this possible!!!...

**Comment by dpad85** [comment] 2018-04-05 11:10
Hi, this is not possible for now with the mobile version. 
You can find the rationale for this in https://github.com/ACINQ/eclair/issues/302 and https://github.com/ACINQ/eclair-wallet/wiki/FAQ#can-i-receive-payments-with-eclair-wallet-.

Closing this issue because it's a duplicate of #302.

**Closed by dpad85** 2018-04-05 11:10 UTC
