### ISSUE TITLE
eclair not sending any channel_update to cln after a while

### ISSUE THREAD

**Issue by daywalker90** [ACINQ/eclair#2717] opened 2023-07-25 09:37 UTC
I noticed that my cln 23.05 node is not receiving any channel_update for 776755x557x1 anymore from the ACINQ node.
 You can see that other nodes are also missing this channel_update here: https://mempool.space/lightning/channel/854051154469650433

I opened an [issue ](https://github.com/ElementsProject/lightning/issues/6344) on the cln repo first, but apparently it's the responsibility of the eclair node to send the channel_update so i hope this is the correct place to raise the issue. I already tried deleting the gossip store and restarting.

I remember that the channel did not miss the direction from ACINQ in the beginning and i have opened a second channel which is also fine for now.

**Comment by t-bast** [comment] 2023-07-25 11:28
That's surprising, becauseI just checked that we did create a channel update for that channel (on July 17th) and we did broadcast it to our peers through the usual staggered broadcast mechanism.

We refresh channel updates every 10 days (since the spec says we should refresh at least every 14 days), so I'm surprised it was somehow dropped.

**Comment by rorp** [comment] 2023-07-25 19:40
Apparently, this is the root cause of https://github.com/ACINQ/eclair/issues/2645

I experienced this bug as well. Fixed by nuking the network database.

**Comment by t-bast** [comment] 2023-07-26 07:30
I don't think these issues are related, in #2645 it was a custom plugin that was generating invoices with invalid routing hints, that's why path-finding couldn't find a route.

**Comment by daywalker90** [comment] 2023-08-06 13:51
I think i kept this "broken" channel open long enough and will close it soon, if there is no easy fix.

**Comment by rorp** [comment] 2023-08-06 17:30
> I don't think these issues are related, in #2645 it was a custom plugin that was generating invoices with invalid routing hints, that's why path-finding couldn't find a route.

AFAIR the symptoms were the same (a lost channel update) and the fix was the same (nuking the network database). @evd0kim correct me if I'm wrong.

**Comment by rorp** [comment] 2023-08-06 17:35
> I think i kept this "broken" channel open long enough and will close it soon, if there is no easy fix.

There's no fix per se. Is I mentioned above there a home remedy: forcing your node to re-sync with the Eclair node. For Eclair it can be done by purging the network database. For CLN it can be something different.

**Comment by daywalker90** [comment] 2023-08-06 17:49
i already deleted the graph if thats what you mean. Didn't help.

**Comment by evd0kim** [comment] 2023-08-06 21:15
> nuking the network database

I can confirm I did this at least once. But I should say that Eclair have settings for whitelisting network announcements peers. So it may be that your peer intentionally ignores you.

**Closed** 2024-07-29 12:38 UTC
