### ISSUE TITLE
Requested mutual close via API/RTL turned into force close

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#1519] opened 2020-08-19 12:50 UTC
```
2020-08-19 12:56:48,372 INFO  f.a.e.io.PeerConnection CON - connection authenticated with 025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4@23.129.64.186:50052 direction=incoming
2020-08-19 12:56:48,372 INFO  f.a.e.io.PeerConnection CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 - using features=features=initial_routing_sync:optional,var_onion_optin:optional,option_support_large_channel:optional,gossip_queries_ex:optional,option_data_loss_protect:optional,option_static_remotekey:optional,gossip_queries:optional
2020-08-19 12:56:48,373 INFO  f.a.e.io.PeerConnection CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 - peer is using features=features=payment_secret:optional,option_data_loss_protect:mandatory,var_onion_optin:optional,basic_mpp:optional,option_static_remotekey:optional,gossip_queries:optional (unknown=5), networks=
2020-08-19 12:56:48,373 INFO  f.a.e.io.PeerConnection CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 - sending sync channel range query with flags_opt=None
2020-08-19 12:56:48,373 INFO  f.a.e.io.PeerConnection CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 - rebroadcast will be delayed by 50 seconds
2020-08-19 12:56:48,374 INFO  f.a.e.i.ReconnectionTask CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 - peer is connected
2020-08-19 12:56:48,374 INFO  f.a.e.i.Peer$MessageLogs CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:262689bacd2ea459df915f4c411c43af5e682c591c3ce6861914e262fa4094e2 - OUT msg=ChannelReestablish(262689bacd2ea459df915f4c411c43af5e682c591c3ce6861914e262fa4094e2,108,107,PrivateKey(3a7a7230028cb48adb93afd38f604102666a172f5c69a93dc955ed8421976b29),023915e5212968dd94b77bbaae4141c3c6d31f7f0078591bc47a09b48e0f9e2991)
2020-08-19 12:56:48,374 INFO  f.a.e.i.Peer$MessageLogs CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - OUT msg=ChannelReestablish(c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22,2687,2686,PrivateKey(71af16c3ea9ddd56eac5958e29108b2da10b06c0df5fa54b97e82ddb3b981988),03941976dd2dab73e5f4e8327b6d4c63272e092e9bfd8a7095588d04e48610480f)
2020-08-19 12:56:48,374 INFO  f.a.eclair.Diagnostics CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:262689bacd2ea459df915f4c411c43af5e682c591c3ce6861914e262fa4094e2 - OUT msg=ChannelReestablish(262689bacd2ea459df915f4c411c43af5e682c591c3ce6861914e262fa4094e2,108,107,PrivateKey(3a7a7230028cb48adb93afd38f604102666a172f5c69a93dc955ed8421976b29),023915e5212968dd94b77bbaae4141c3c6d31f7f0078591bc47a09b48e0f9e2991)
2020-08-19 12:56:48,374 INFO  f.a.eclair.Diagnostics CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - OUT msg=ChannelReestablish(c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22,2687,2686,PrivateKey(71af16c3ea9ddd56eac5958e29108b2da10b06c0df5fa54b97e82ddb3b981988),03941976dd2dab73e5f4e8327b6d4c63272e092e9bfd8a7095588d04e48610480f)
```

logs after sending `close` via API:

```
2020-08-19 12:56:49,288 INFO  f.a.eclair.Diagnostics CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - IN msg=ChannelReestablish(c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22,2687,2686,PrivateKey(6129afc1f279984d136210b520775325b00f18268fe494687334651211523bc2),03d9f0881183f3458da4b2cea956966eaee84933981296e4586ee7c21d05b566f8)
2020-08-19 12:56:49,289 INFO  f.a.eclair.Diagnostics CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:262689bacd2ea459df915f4c411c43af5e682c591c3ce6861914e262fa4094e2 - IN msg=ChannelReestablish(262689bacd2ea459df915f4c411c43af5e682c591c3ce6861914e262fa4094e2,108,107,PrivateKey(a2964c6afe380d41c6e3af1be21a48d0e1a1ff0626cb4fbf7ac94ef812089ec9),02585a7fa001a00e9a3e2934c16d97ce9c3a57d516ab35c70f091d8bf42351a9c4)
2020-08-19 12:56:49,289 INFO  f.a.e.i.Peer$MessageLogs CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - IN msg=ChannelReestablish(c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22,2687,2686,PrivateKey(6129afc1f279984d136210b520775325b00f18268fe494687334651211523bc2),03d9f0881183f3458da4b2cea956966eaee84933981296e4586ee7c21d05b566f8)
2020-08-19 12:56:49,289 INFO  f.a.e.i.Peer$MessageLogs CON n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:262689bacd2ea459df915f4c411c43af5e682c591c3ce6861914e262fa4094e2 - IN msg=ChannelReestablish(262689bacd2ea459df915f4c411c43af5e682c591c3ce6861914e262fa4094e2,108,107,PrivateKey(a2964c6afe380d41c6e3af1be21a48d0e1a1ff0626cb4fbf7ac94ef812089ec9),02585a7fa001a00e9a3e2934c16d97ce9c3a57d516ab35c70f091d8bf42351a9c4)
2020-08-19 12:56:49,289 INFO  f.a.e.i.Peer$MessageLogs n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - OUT msg=Shutdown(c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22,ByteVector(22 bytes, 0x00145e574f15402a21033dd7181460e3ab8342a2b67a))
2020-08-19 12:56:49,289 INFO  f.a.eclair.Diagnostics n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - OUT msg=Shutdown(c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22,ByteVector(22 bytes, 0x00145e574f15402a21033dd7181460e3ab8342a2b67a))
```

channel apparently still not closing, sending `close` again. Reply: `"579854x2998x1": "closing already in progress"` 

logs:

```
2020-08-19 13:00:40,701 WARN  f.a.e.channel.Channel n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - closing already in progress while processing cmd=CMD_CLOSE in state=NORMAL
```

a few minutes later another try via RTL close command (*not* force close). RTL replied with `close successful` but channel was actually force closed:

``` 
2020-08-19 13:04:46,966 WARN  f.a.e.channel.Channel n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - force-closing channel at user request
2020-08-19 13:04:46,996 INFO  f.a.e.channel.Channel n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - tx generation success: desc=main-delayed-output txid=ef08f7722dd9945cbc985ff19e1faaaae7148cfbe17e173528f0a2b2b238f80e amount=Satoshi(4944725) tx=020000000001018942939d53073d1e397c5349185582976ab818f8deb74afcbe82c92bb27a37240100000000600300000155734b00000000001600145e574f15402a21033dd7181460e3ab8342a2b67a034830450221009e4ad6b62aa37645e8d3534d26766494709f624f4d5e4de201d34ae7d0c6763e022018d85ddd240435822c058f3cc00cf9aac646939b8c958452298c061b57856f7101004d63210339537efd2e179a75bb36b1643aa3b8ca54326528cbf7c941112856b4b32248ef67026003b275210354859323f4fceb9fa65161548d0cb71e80b2dd7dcb696b17524bc83c6c853ad968ac00000000
2020-08-19 13:04:47,058 INFO  f.a.e.channel.Channel n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - publishing txid=24377ab22bc982befc4ab7def818b86a9782551849537c391e3d07539d934289
2020-08-19 13:04:47,058 INFO  f.a.e.channel.Channel n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - publishing txid=ef08f7722dd9945cbc985ff19e1faaaae7148cfbe17e173528f0a2b2b238f80e
2020-08-19 13:04:47,065 INFO  f.a.e.b.b.ZmqWatcher - publishing tx (isRetry=false): txid=24377ab22bc982befc4ab7def818b86a9782551849537c391e3d07539d934289 tx=02000000000101c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c2301000000008de957800230c9000000000000160014d7a69870ee6301092bd513443c90804615c9df7ccf734b0000000000220020fcdf3ac50f3eda5da756a4afb2726e44843837bc8a32d8cae408f74e21ccc10e0400483045022100e0b4e1b04d97b8d919d8d0e28a2a83845171189d925669a62783b9de25f3bc1402200f705f4904b5ace3c3974d29dc3750ea537d3342743acf96217a65457eff0a4e01483045022100901899556798417fef2b3c810566e82c805c33cda298da9cc43444fd6cd4ff5102200788f7216b63e2f78453423d0a9ddfff0a74f412c453a3d7f70a6a7b235845fe01475221029424949747218977312b7ddc107c7f90e774ce4f878031830b569600a21052a42103efcb8d8a63b443d308a2e99a919989bcedeb16906daedcd7a23b34389353e44e52ae7c00c620
2020-08-19 13:04:47,066 INFO  f.a.e.b.b.ZmqWatcher - txid=ef08f7722dd9945cbc985ff19e1faaaae7148cfbe17e173528f0a2b2b238f80e has a relative timeout of 864 blocks, watching parenttxid=24377ab22bc982befc4ab7def818b86a9782551849537c391e3d07539d934289 tx=020000000001018942939d53073d1e397c5349185582976ab818f8deb74afcbe82c92bb27a37240100000000600300000155734b00000000001600145e574f15402a21033dd7181460e3ab8342a2b67a034830450221009e4ad6b62aa37645e8d3534d26766494709f624f4d5e4de201d34ae7d0c6763e022018d85ddd240435822c058f3cc00cf9aac646939b8c958452298c061b57856f7101004d63210339537efd2e179a75bb36b1643aa3b8ca54326528cbf7c941112856b4b32248ef67026003b275210354859323f4fceb9fa65161548d0cb71e80b2dd7dcb696b17524bc83c6c853ad968ac00000000
2020-08-19 13:04:47,070 INFO  f.a.e.i.Peer$MessageLogs n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - OUT msg=Error(c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22,ByteVector(19 bytes, 0x666f72636564206c6f63616c20636f6d6d6974))
2020-08-19 13:04:47,071 INFO  f.a.eclair.Diagnostics n:025898908ba87918c1db427e0303071914a405c1dd810c97fefeca852dac7e80b4 c:c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22 - OUT msg=Error(c90c53825dff99a358472087f25d5341d9b21d9ab8d15a6d0ba912bc13b16c22,ByteVector(19 bytes, 0x666f72636564206c6f63616c20636f6d6d6974))
```

Not sure if RTL or eclair is a t fault here. Pinging @ShahanaFarooqui

**Comment by t-bast** [comment] 2020-09-01 07:49
The logs indicate that eclair explicitly received a `force-close` request, it would not print that with normal `close` request.
I'm guessing (just a guess) that RTL transforms the `close` into a `force-close` after X attempts or something like it?

It's expected that normal closing may take time because all HTLCs have to settle, and the peer has to collaborate.

**Comment by t-bast** [comment] 2020-10-01 07:21
@ShahanaFarooqui could you chime in on this to explain if that is RTL's behavior?

**Comment by ShahanaFarooqui** [comment] 2020-10-01 15:31
@t-bast @viaj3ro I have opened below issue assuming that the confirmation message might have been the reason of confusion. Other than that, I am unable to see any other possibility to trigger force close from RTL without user's knowledge. It will be out in the next released (hopefully in next 2-3 days).

`Channels table has 2 separate buttons for "Close Channel" and 'Force Close Channel". And, force close can ONLY be triggered by clicking on the "Force close" button.

However I am assuming that due to identical confirmation messages for close and force close, one of our user unintentionally force closed the channel rather than normal close. It can be avoided in future by changing the confirmation message for force close.

https://github.com/Ride-The-Lightning/RTL/issues/501`

**Comment by t-bast** [comment] 2020-10-05 07:29
Thanks for the explanation.
I don't see how a close could be converted into a force-close on the eclair side either, so closing this issue for now.
@viaj3ro if the issue reproduces, please re-open and share more logs.

**Closed by t-bast** 2020-10-05 07:29 UTC
