### ISSUE TITLE
Eternal pending transactions with Yalls.org

### ISSUE THREAD

**Issue by ric2b** [ACINQ/eclair#278] opened 2017-12-13 17:13 UTC
First of all thank you, eclair already shows the potential and gets me really excited for LN!

I've been trying it out and it seems to work well with starblocks but I can't get a smooth experience with Yalls.org. I know the Yalls node is made by a different team but even it the problem is on their side, I do many transactions that have been Pending (almost an entire day), it would be nice if they could be removed after some time.

I did get an error message once stating that no route was found so I tried opening a channel directly with Yalls node (02011549da333502f4c7ff2395ee5d110ab865d55f580fb360799f4f95e1be9066@45.77.115.33), but I was only able to make one successful transaction, all others have also been Pending (one actually failed).

I don't know if I can provide more debug information, please tell me if I can.

Thank you for making eclair and contributing to the LN protocol, it's looking really cool and I can't wait to test new versions and see it evolve! :)

**Comment by pm47** [comment] 2017-12-13 19:49
We discovered a bug two days ago that caused payments to be stuck in PENDING state (fixed since c43c009f94a12831d11bbcee3f3ffccc913327e5).

But this bug would also occur if you were paying starblocks, so that may be something else. Are you running an eclair node (on desktop) or eclair-wallet (mobile app)?

Were you able to reproduce the issue with only one channel connected to the yalls node?

A payment PENDING has already been sent, so you can't remove it. After that, it can only succeed, fail or timeout. You can't fail it yourself because the node you are directly connected to may have forwarded it to another node. If it lingers for too long, it will eventually timeout, the channel will be closed and you'll get your money back.

**Comment by ric2b** [comment] 2017-12-14 00:50
I'm using the eclair-wallet on Android, version 0.2.1 (latest available from the playstore), it hasn't received an update in a few weeks so I guess it still has that bug.

But as far as I can remember all payments to starblocks (I must have done about 15 over the last 2 days) were successful.

What do you mean with only one channel connected to yalls? If you mean with all other channels closed then no, I haven't tried it yet, I will and I'll report back.

And ok, that makes sense about not being able to remove the pending payments.

**Comment by ric2b** [comment] 2017-12-14 01:02
Hmm,  it seem like I can't close the channel I have open with node 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134.

It's in shutdown state but it doesn't seem to have created an on-chain transaction. I tried to unilaterally close it but nothing happens, even after restarting the wallet,

I can't make new transactions to Yalls or Starblocks now, they're both pending. I guess it's an issue with the communication or compatibility with Yalls node? (02011549da333502f4c7ff2395ee5d110ab865d55f580fb360799f4f95e1be9066)

**Comment by Sgt-Miller** [comment] 2017-12-14 04:00
Mobile wallet.      
I have two channels with two LN slack tip bots.
My node ID is 038be07b42ce34871ae7d36d4b9aeb3219591db4bf40a8262954a88cb0aa58ec71
The LN bots node ID are 
03ba998c7cfc9e48d59bf5350ebb54356b75ba9cce6a6284628eda6bf389ce452c
and 02aa168b8db65e37156841b3bc1e80982dcc00608cf07a57f672396b2719dd238f
Payment to ln bot works
Payment to htlc.me works
Payment to Starbucks is pending
Payment to Yalls.org is pening
Will be glad to provide more info if needed

**Comment by pm47** [comment] 2017-12-14 11:13
@ric2b 

> Hmm, it seem like I can't close the channel I have open with node 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134.

> It's in shutdown state but it doesn't seem to have created an on-chain transaction. I tried to unilaterally close it but nothing happens, even after restarting the wallet,

Ok, this looks like the bug we fixed earlier this week. That bug wasn't in eclair-wallet but in relaying eclair nodes, the one you were connected to (0393...) was affected.

When you try to close a channel, the first thing to do is wait for pending htlcs (payments) to clear, that's the purpose of SHUTDOWN state. In your case, the pending htlcs will never clear and will eventually timeout (can't say exactly when, value is per-payment), which will cause your node to unilaterally close the channel by publishing the current commitment. You will then need to wait for 144 blocks before seeing an incoming transaction, because you were the one initiating the unilateral close. Best thing is to let this play out and make sure that you eventually get your money back. This looks like a very convoluted scenario, but at least it demonstrates that even when things go awfully wrong you still don't lose your money.

Note that it is not currently possible to cut short the wait in SHUTDOWN state and unilaterally close the channel before pending htlcs timeout, we will fix that.

> I can't make new transactions to Yalls or Starblocks now, they're both pending. I guess it's an issue with the communication or compatibility with Yalls node? (02011549da333502f4c7ff2395ee5d110ab865d55f580fb360799f4f95e1be9066)

It is difficult to tell, maybe you are connected to other instances of eclair, that still have the bug, I can't reproduce it. Try closing all other channels and open a channel to 0393... or directly to 0201...

**Comment by ric2b** [comment] 2017-12-14 11:18
Ok, thanks for the explanation, really enjoying learning more about it :)

I'm thinking about running a testnet LN node, do you think it would be helpful for you or at this point it would have no benefits to testing?

**Comment by pm47** [comment] 2017-12-14 11:20
@ric2b 

>>But this bug would also occur if you were paying starblocks, so that may be something else

>I have two channels with two LN slack tip bots.

@Sgt-Miller what I said only applied if you had a direct channel to 0393... because the shortest route to starblocks would be through this node, which don't have the bug anymore. In your case the payment routes may go through an eclair node that is still affected by the bug.

**Comment by pm47** [comment] 2017-12-14 11:21
> I'm thinking about running a testnet LN node, do you think it would be helpful for you or at this point it would have no benefits to testing?

Sure! but please wait for 0.2-alpha8, we will release it asap.

**Comment by ric2b** [comment] 2017-12-14 14:54
Ok, now that I've closed all channels and re-opened on to 0393 I can make payments to starblocks again but payments to Yall's are now failing (after 5 attempts by the wallet) instead of pending, which seems like progress to me :)

I've tried 6 times now and these are the failures (They happen in the same order with the same channels, even when paying for different articles):
1. Unknown next peer (Origin channel: 1323580000ef0001)
2. TemporaryChannelFailure (Origin channel: 1323580000f30001)
3. TemporaryChannelFailure (Origin channel: 13248f00008c0001)
4. Unknown next peer (Origin channel: 1322880000d10001)
5. Unknown next peer (Origin channel: 1322c20000590000)

**Comment by pm47** [comment] 2017-12-17 14:03
@ric2b please try again with latest version (0.2.2), first payment may be slow because there is some cleaning up of channels in the background, but after that things should be fine.

**Comment by ric2b** [comment] 2017-12-17 20:05
Yep, it worked great for some time but now it's failing again due to:

1. RemoteFailure (of 0393, no channel ID given)
2. Local Failure (route not found)

I've tried opening a new channel to 0393 but the same happened. I then closed the older channel and same result. I have now closed both channels (cooperatively) and am opening a new one to 0393. 

I'll report back when it confirms and I'm able to test it again.

**Comment by pm47** [comment] 2017-12-17 22:04
That's a "normal" error: the only route that your mobile found didn't work out, and there was no alternative, so the payment failed.

This particular route failed because the only channel 0393 had with yalls had just been closed. Opening more channels with 0393 right away won't change anything, if no route exist between 0393 and yalls.

So in that case you should either wait a little (because the network changes constantly and new routes are created/destroyed all the time), or you could open more channels to other nodes instead of just connecting to 0393.

I'm closing this ticket because the original issue has been fixed.

**Closed by pm47** 2017-12-17 22:04 UTC
