### ISSUE TITLE
Channel status on "syncing" even after 6 confirms

### ISSUE THREAD

**Issue by Sgt-Miller** [ACINQ/eclair#262] opened 2017-12-07 10:52 UTC
Eclair mobile wallet  
I made a channel with autoconnect, it works fine, bought a Scala Chip Frappuccino too.
I created another channel with yalls.org . They use lnd
The channel has 6 confirms. 
The channel with acniq has status of NORMAL
The channel with yalls.org has status of SYNCING . Its been in that status for quite some time.
I tried a payment to yalls.org and the transaction is in status of PENDING.
Here are the screenshots. 
https://my.mixtape.moe/eedzuo.png
https://my.mixtape.moe/glekwj.png

**Comment by dpad85** [comment] 2017-12-07 11:19
Hello,

This is an issue on LND which has been reported here: https://github.com/lightningnetwork/lnd/issues/458. 
It has been fixed in this pull request: https://github.com/lightningnetwork/lnd/pull/457

You can close the `SYNCING` channel (it will be an uncooperative closing) or wait till the fix is rolled out on Yalls and see if the channel goes to `NORMAL`.

In the meantime, if you still want to have a channel with Yalls, you can open a new one and make sure that your eclair wallet does not shut down. After 2 confs, the channel will go to `NORMAL`. The `SYNCING` issue appears only if there is a disconnection during the funding.

Leaving this issue open since it can be useful for other users.

**Comment by pm47** [comment] 2017-12-08 16:14
Hey @alexbosworth can you let us know when you have updated  yalls node to lnd > https://github.com/lightningnetwork/lnd/commit/c0e88cd8a875781221bc14cb449cfaf262687b91? Thanks!

**Comment by alexbosworth** [comment] 2017-12-08 17:30
Y'alls testnet and mainnet nodes are currently on https://github.com/lightningnetwork/lnd/commit/839ce0689e740c912671f84c0867aaa768ea9767 which should be the latest

**Comment by pm47** [comment] 2017-12-08 17:34
Confirmed! Issue has disappeared. Thanks!

**Closed by pm47** 2017-12-08 17:34 UTC
