### ISSUE TITLE
Payment is sent successfully, but check payment (from sender) always return false, and repeat send will lost money!

### ISSUE THREAD

**Issue by wymcmh** [ACINQ/eclair#573] opened 2018-04-24 08:58 UTC
I deploy the java version eclair: eclair-node-0.2-beta2-7598615.jar, and bitcoin core version 0.16.
I create a payment on htlc.me and pay with eclair-cli, the payment is sent successfully, but eclair-cli checkpayment always return false.
And when I repeat send the payment, my channel's balance is deducted, but the recipient's account balance **no longer increases**, these **money lost in the channel!**

**Comment by sstone** [comment] 2018-04-26 13:35
`checkpayment` checks that a payment has been received, not sent, so that's normal.
Money is not lost in the channel, it is transferred to the other side. What is probably happening here is that htlc.me allows you to pay the same payment request several times without updating the balance. I will try and update this ticket.

**Comment by dpad85** [comment] 2018-06-12 15:10
> What is probably happening here is that htlc.me allows you to pay the same payment request several times without updating the balance.  I will try and update this ticket.

This is still what's happening. There is no reasons for eclair to not complete successive identical payments. The issue is on htlc.me side: payments are completed but balance is not updated.

Closing this issue. Thanks!

**Closed by dpad85** 2018-06-12 15:10 UTC
