### ISSUE TITLE
Funds are not returned to bitcoin-qt wallet when closing channels

### ISSUE THREAD

**Issue by AndySchroder** [ACINQ/eclair#290] opened 2017-12-17 03:22 UTC
Funds are not returned to bitcoin-qt wallet when closing channels. Where are the supposed to go? Is there an internal wallet in eclair? If so, how do I know the balance of it?

**Comment by pm47** [comment] 2017-12-17 14:07
Funds should be returned to bitcoin core, but timing depends on how the channel was closed:
- unilateral close initiated by your node -> wait for 144 blocks
- unilateral close initiated by remote -> immediate
- mutual close -> immediate

Can you provide your `eclair.log`?

**Comment by yogafan** [comment] 2017-12-19 14:23
I noticed this too.  I forced a channel closed on Dec 14 and funds were never returned to the wallet.  I was expecting some kind of delay but your comment about 144 blocks says the coins are overdue.

**Comment by pm47** [comment] 2017-12-19 14:47
Yes, I just figured it out while working on another ticket. It turns out that we are using local `toSelfDelay` instead of remote's when claiming the funds, which is why we can't resolve our output. This will occur if you have a channel with an lnd node for example.

@yogafan is the channel still in CLOSING state?

**Comment by yogafan** [comment] 2017-12-19 15:50
@pm47 After forcing the channel closed, I restarting eclair and that particular channel disappeared from the GUI.  I don't know what happened to it.

**Comment by pm47** [comment] 2017-12-19 16:32
@yogafan ok, that's what I expected: since there was apparently no output for itself, eclair considered the channel closed and cleaned it up after the commit tx got enough confirmations. So to be clear it is wrong, but consistent with the issue at hand.

**Comment by pm47** [comment] 2017-12-19 16:36
@yogafan if you can build https://github.com/ACINQ/eclair/pull/296/commits/0d8c08dc51f124e2ebc0fe72502f1df0491b8b13 and make sure you can't reproduce anymore, that'd be great.

**Comment by yogafan** [comment] 2017-12-19 21:36
@pm47 I spent some time today trying to get a dev environment working on this with IntelliJ IDEA on Windows 7 pro but I failed.

**Comment by pm47** [comment] 2017-12-19 22:30
eclair is pretty easy to build, you just need the JDK and maven. Did you take a look at [BUILD.md](https://github.com/ACINQ/eclair/blob/master/BUILD.md)?

**Closed** 2017-12-20 17:35 UTC
Labels: bug
