### ISSUE TITLE
Node crash after PgUtils couldn't obtain lock

### ISSUE THREAD

**Issue by engenegr** [ACINQ/eclair#1869] opened 2021-07-11 15:33 UTC
Sorry for very few logs. 

The crash has happened literally when I was writing report about another issue.

```
ng 16 channel announcements and 82 updates, format=COMPRESSED_ZLIB
2021-07-11 14:54:58,519 WARN  c.z.h.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m45s94ms684µs301ns).
2021-07-11 14:56:39,830 WARN  c.z.h.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m23s108ms814µs51ns).
2021-07-11 14:56:54,499 ERROR k.module.ModuleRegistry - Reporter [Kamon APM Reporter] failed to process a metrics tick.java.lang.OutOfMemoryError: Java heap space

2021-07-11 14:56:55,854 ERROR f.a.e.d.p.PgUtils - cannot obtain lock on the database.
java.lang.OutOfMemoryError: Java heap space

2021-07-11 14:56:56,516 ERROR f.a.e.d.p.PgUtils - db locking error is a fatal error
```

Now I'm trying to do something urgently and it looks like your default config values from [here](https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/resources/reference.conf) may be working. I'm testing now
```
        max-size = 10 // recommended value = number_of_cpu_cores * 2
        connection-timeout = 30 seconds
        idle-timeout = 10 minutes
        max-life-time = 30 minutes
 ```

**Comment by t-bast** [comment] 2021-07-12 06:49
> java.lang.OutOfMemoryError: Java heap space

It looks like you're exhausting your machine's limits, that's not something we can do much about.
These logs are very strange though:

> 2021-07-11 14:54:58,519 WARN  c.z.h.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m45s94ms684µs301ns).
> 2021-07-11 14:56:39,830 WARN  c.z.h.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m23s108ms814µs51ns).

Either that's because you're at your machine's limits (what do system perf counters say?) or it's the cause of the issue (is there a bug inside Hikari that could leak memory?).

**Comment by engenegr** [comment] 2021-07-12 16:34
> It looks like you're exhausting your machine's limits, that's not something we can do much about.
These logs are very strange though

Yes. Machine is weak. After update it runs on 2-3% CPU though.

![eclair-update](https://user-images.githubusercontent.com/15425710/125323796-80e70280-e33f-11eb-8a94-bc5e87a0e36b.png)

I was lucky your default settings in reference.conf helped me and it currently runs. 

But also situation gives a hint that there may be some problems during client initialization and migration from old database.

**Comment by t-bast** [comment] 2021-07-13 06:35
> Yes. Machine is weak. After update it runs on 2-3% CPU though.

I think the CPU isn't really a problem in your case, it's rather a memory issue since the error log is `java.lang.OutOfMemoryError: Java heap space`. If possible, can you increase the amount of heap memory eclair can use?

Usually eclair doesn't consume much CPU power, IIRC in your case you have a single CPU (or a small number of them), right?
I think that maybe the high CPU usage you're seeing is because you're context-switching a lot.
It would be interesting to have system metric about context switches and the time spent there, if you have access to that.

**Comment by t-bast** [comment] 2021-07-16 15:28
Closing this issue as we can't do much for `java.lang.OutOfMemoryError: Java heap space` errors, feel free to re-open if you find a bug that may be responsible for a memory leak inside eclair.

**Closed by t-bast** 2021-07-16 15:28 UTC
