### ISSUE TITLE
Channel stuck in Closing due to "cannot publish tx: reason=66: min relay fee not met (code: -26)"

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#602] opened 2018-05-19 12:13 UTC
I had a few channels that were closed due to fee issues.

They had small incoming balances (904 satoshi in this case).
When it came to publish the toLocal timeout tx from commitment tx that was published we get this error:

`eclairdebug.2018-05-18.log:16:01:25.354 ERROR akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - cannot publish tx: reason=66: min relay fee not met (code: -26) txid=8724c404a4a0dc4846368c04236d56639098455e01fddfd477314d033ade73e0 tx=02000000000101a5c3d4efb0df5b2c5440f77d990270572878e91b2df0e958147fc4760f348bb00000000000f000000001100300000000000017a914afedceb5c9733c5a7505d4b520d123dd1fc5ffda870347304402202b53435cf524ac48187fbd095d8180ce40bc3111b162641facc0d616b91a14f502203f3e9a3602dfb62564e63b0044fa0fc1d1115ef3e32da673dafb79534d22258101004d632102ced73eacd36a1f801b4b4291ea16eddb174eca44dd247d6b77a1bcba9b50598e6702f000b275210290bc851d23c11be5629d532d0cce7051171ec0e1cb39369b6581f80a18ee0ee868ac00000000`

Which makes sense. As is below the default of 0.00001 - 1000 sat btc/kb which is what my btcd is running with.
This tx has 120 Sat fee.  which is 506 Sat/KByte - hence why not relayed.

**Comment by n1bor** [comment] 2018-05-19 16:46
My fee rates at the time were:
21:31:55.843 INFO   fr.acinq.eclair.Setup - current feeratesPerKB=FeeratesPerKB(25315,3285,1000,1000,1000,1000) feeratesPerKw=FeeratesPerKw(6328,821,250,250,250,250)

So the 6 block was FeeratesPerKw=250
Weight is 482 https://github.com/ACINQ/eclair/blob/449c3071327d1c47b0bca07862afd0e67dd07d04/eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala#L91
So fee is 482*250/1000 = 120.
Therefore fee was computed correctly. Issue is that this is below the min relay fee of 1000 sat/kbyte.
So need a floor on the fees in Sat/KByte. So need the byte size of all tx as well as the weight.

Everyone agree with this?

**Comment by n1bor** [comment] 2018-05-19 16:50
So I think this is a serious issue as not because the output were very small. Any size output would have this issue whenever fee rates are below 500 sat/kweight for 6 blocks. No funds lost - but have to manually construct a tx to spend them back to yourself.

**Comment by Thoragh** [comment] 2018-05-21 23:03
I am running into the same issue. The vsize of the transaction is 122 vbyte while the fee is only 120 sat which is not enough.
The raw tx is: `02000000000101b34ee0da482b70aebc1e2a859da7d28ba0cb4e3fed22a98bc20db76553cfa8ea00000000009000000001383601000000000017a914b80d8d8bd669a19c91d8206360ea411e63cd3ba38703473044022024f6d19c2697400f84bc25a1c117c87f5aaffc9472b81d3529a058905ec82a52022038ef0c595f0df40e8e0199662654574a8f94be0786dfc2e17ec54a56205bc26901004d632103308c873ee5c9df42a75dd5548059034307055dcca259b8fecdb19f50b6aa4c7267029000b2752102aeb6a80c20a6af7af3755ddd22b457519958e88833a2cc9fa4c6bc3781c662b968ac00000000`

> So fee is 482*250/1000 = 120.
> Therefore fee was computed correctly. Issue is that this is below the min relay fee of 1000 sat/kbyte.
> So need a floor on the fees in Sat/KByte. So need the byte size of all tx as well as the weight.
> 
> Everyone agree with this?

The math rounding down is a problem when its trying to send with the minimum fee but it doesn't explain why the fee is 2 satoshi too little. is the transaction weight of 482 wrong?

**Comment by sstone** [comment] 2018-05-22 12:49
A vzise of 122 matches a weight of 484 (and not 482) but it's a minor issue. The real problem is that with very low fee rates we may end up with txs that cannot be relayed, because of the mismatch between weight-based and size-based fees. An easy fix is to set `eclair.min-feerate` to 2.

**Comment by nekotribal** [comment] 2018-05-22 20:39
Got the same issue.
`2018-05-22 17:39:20,842 ERROR f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - cannot publish tx: reason=66: min relay fee not met (code: -26) txid=30cabf6612e7c9cc85233d8fc4a9fe82746cefc92b6e3e8f67d85140ad588aed tx=02000000000101a9a76a6f21b759ef0e42394ea34cc39099a82e84c38b89195e89255292cbf6a000000000000000000001629909000000000017a91422fc48e12c6fdae68a63f399464bacc396878a398702483045022100ad2aa3deff4ed80a75bc1c2990edc499474c9ba4b2145afa83849d1ff5c264d8022000b1f30b4fcdb1913d15bfb918065b81d6b28e971e58b8f16c0946ca1828d7300121034a8c999b5546f8d2f9b3a1c2ae0c56e617b6fba45cc2e4bd38fade0af1c6240300000000
`

**Comment by sstone** [comment] 2018-05-23 08:30
@n1bor yes it looks correct (it could probably be simplified a bit, but it's already quite compact). It's a bit advanced though and I'll try to find another way that does not involve running code (probably through force closing the channel again) and update this ticket. And we probably need a way to boost our `claim our outputs` txs.

**Comment by n1bor** [comment] 2018-05-23 21:30
Arh - this does not always work. If their remote commit was published then they have signed our tx with the low fee. So there is no way I can recreate with a higher fee! 830724369 msat gone then I think? Or I need to find a miner who will take a low fee tx?

**Comment by ZmnSCPxj** [comment] 2018-05-24 06:33
C-lightning internally adjusts feerates of < 253 to 253: https://github.com/ElementsProject/lightning/pull/1251

This actually causes C-lightning to disagree with other LN implementations during low fee times, but is the only way to prevent this "fee too low" error when interacting with `bitcoind`.

**Comment by nekotribal** [comment] 2018-05-24 10:07
I'll describe my case further, as it turned out to be more complex after some talking with @sstone (thanks again!)

Few days ago, I opened a channel, and tried to close it soon after. Funds wasn't used, all of capacity was on my side. I initiated channel closing as well. Channel id was `34337188f1288df36ec47774a441724da210086d629fbc098f375d6ccba6d231`, funding tx `30d2a6cb6c5d378f09bc9f626d0810a24d7241a47477c46ef38d28f188713334`
While closing, two tx's were made: 
1. `a0f6cb925225895e19898bc3842ea89990c34ca34e39420eef59b7216f6aa7a9` that was confirmed, and spent funds to `bc1qg799rjlhpmnz44qc45eg4tqmul80jw35nwej67` address, which I don't seem to control, and
2. `f37858e5f4ffc831689efdb1c230faf10050c37bda840c992be73cd20b9d5f04`
hex `0200000000010134337188f1288df36ec47774a441724da210086d629fbc098f375d6ccba6d2300100000000ffffffff01399c09000000000017a91422fc48e12c6fdae68a63f399464bacc396878a3987040047304402206b2aeb04da99455b20b5b6a30a7a3fa4dc54b51e385dc5a34c4793193319eeb102200bd7164733aa33e94cf21a7419a79197fb9a7b458b8a7240505bc2438f4be0a20147304402206566a80dda62ee5dd813faaa70a3c24dcecadb669214e80f301db9d4afc187b2022063832608757261a4fd2b388ed17cf07f4e6e91aa60b1913ee2e943132e2df56101475221026ea657e9ef221a26c5eb1a0edf8f053698b95ec21dd4f8ecf49fc0e336ba2fa82102f4a403117375b9b93059f5851ba3045bb9278ffa36cc8500c974e1d7c10baba852ae00000000`
which was rejected by the network, but tried to spend to my address `34t187XHXPhpbAnJiBUpSj2QBxPNoS3aqw`.

The important detail is that somewhere at this point I started changing my `addresstype` setting in bitcoind. Initial setting was `p2sh-segwit` and was then changed to `bech32`. Unfortunately I can't remember when exactly I changed it. Today i tested changing it back and forth.

Summary:
`bitcoin-cli listunspent` doesn't see these funds (obviously)
My wallet recognizes `30d2a6cb6c5d378f09bc9f626d0810a24d7241a47477c46ef38d28f188713334` tx but does not recognize `a0f6cb925225895e19898bc3842ea89990c34ca34e39420eef59b7216f6aa7a9`
Tried to `-rescan` in bitcoind on both `p2sh-segwit` and `bech32` addresstypes.
@sstone thinks `bc1qg799rjlhpmnz44qc45eg4tqmul80jw35nwej67` is my address, but my bitcoin-cli doesn't see it.

**Comment by sstone** [comment] 2018-05-24 10:59
@ZmnSCPxj  thanks, somehow I missed this ... (and it's nice to see you here !)

**Comment by ZmnSCPxj** [comment] 2018-05-24 11:55
A friend saw @n1bor comment on #lightning-dev and pointed me here.

**Comment by sstone** [comment] 2018-05-24 12:31
@nekotribal's problem is a bit different: there are some interactions between eclair and bitcoin-core, to fund a new channel but also to get the address to send the funds to when the channel is closed. So changing your bitcoin core `adresstype` while you have open channels can have side effects and is not recommended (our README says use `p2sh-segwit` which is the default and will produce addresses that are understood by all wallets).

**Comment by gustavonalle** [comment] 2018-05-26 22:38
I am in the same situation as @nekotribal. Eclair did two tx, one to close the channel (got confirmed) and another (claim tx) got rejected by bitcoind due to min relay fee not met. I haven't change the address type on bitcoind though.

In the close channel tx, the output is to a bech32 addresss that I do not control, so I can't redo the claim tx to spend that output.

**Comment by n4spd** [comment] 2018-05-28 08:56
n1bor, how do I run your script?

**Comment by sstone** [comment] 2018-05-28 09:03
Quick recap:

- to avoid this bug just set `eclair.min-feerate to 2` in your eclair.conf file, that will work with existing nodes (you just need to stop and restart your nodes).
- if you're affected by this bug you can recompute and publish a valid `claim my output` tx using the `forceclose` API call (it is available from the API but not the GUI when channels are in CLOSING state, so you need to enable the API first). First you have to set `eclair.min-feerate to 2`and restart eclair, then forceclose the channels that are stuck.  Do this * ONLY * if there was a specific `cannot publish tx: reason=66: min relay fee not met (code: -26)` in your logs, this is not a generic solution to speed up the closing process (see below) !
- when a channel is "unilateraly closed" and your commit tx is published, your output in this commit tx cannot be spend right away, you have to wait between 144 blocks (eclair and c-lightning) and 1200 blocks (if you've opened a large channel with a lnd node) so it's normal to see channels remaining in CLOSING state for some time. Once this delay has passed, eclair will publish a tx that return funds to your wallet.

**Comment by sstone** [comment] 2018-05-28 09:09
@n4spd please try the forceclose method described above, and if you need any help please checkout our [gitter](https://gitter.im/ACINQ/eclair), thanks

**Comment by n4spd** [comment] 2018-05-28 20:07
@sstone used json api to forceclose channel id and got result:
{
  "result" : "ok",
  "id" : "eclair-node"
}

however, eclair log still shows error:
cannot publish tx: reason=66: min relay fee not met (code: -26)

**Comment by sstone** [comment] 2018-05-28 20:45
@n4spd you need first to set eclair.min-feerate to 2, restart eclair and then forceclose again otherwise you'll just republish the same tx with the same fee

**Comment by n4spd** [comment] 2018-05-28 22:04
I did set min-feedrate to 2 but last error might be an old one.  I now see in the eclair log:

2018-05-28 13:07:44,812 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb - tx generation success: desc=main-delayed-output txid=865739123ee76f257101cb270e1ef9e7d5f3e8093a9d220ea9072dbe791d08ad amount=128202 tx=02000000000101d681c7ffba961f8ac8e49e48e409eccf7596f72b492430decccf9081ed940e3e00000000009000000001caf401000000000017a9140c268e1cfd549df4c269958fae253e013da716ea870347304402201ee92c842132289ec5d419f72c9e7b42b6a104e21f2038204114040796afc71e02203e690e607e34d08845fb54e78892f86866b6ce7bbc92fde3685957e266e9ced901004d63210226ac4d994613cffbc5db677ca43ba36e4411b3f35a4c9a81333c32a42665c08067029000b2752103355dd461d0517fec30ab4785f127f77830fec8d34aa0028922f6de28af8859e568ac00000000

So, am I correct that after 144 blocks, there should be a log entry with desc=claim-p2wpkh-output that will be published?

**Comment by mautematico** [comment] 2018-05-29 04:56
Interested on an even smaller tx causing problems? :)

`020000000001013b72ead2a813fe83bc4a5927e48fc5d9b5f7a9225345bb37207d350880e5e2dd00000000000000000001192709000000000017a91412d39d75d67b27e0d7f0a490dc85fc2c04d86ec78702483045022100a14ee0f0705612870f7b232528cb754cce5232f0f062f9a33e82a9d7cc8dace3022007b6d3707d8aeb57744748a4fbdf06b85cb62743dbe2dad0dce8016422e0d2530121032ea17cfa33d2ce51f25f744f35c9b9be6376bfd2f1f41178b3c2fd92fd6c333d00000000`

Claim tx of 111 vbytes, paying only 109sat.

I will try to use @n1bor's script

**Comment by mautematico** [comment] 2018-05-29 05:56
It worked.

Easy as using `blocks_6 = 1024`. 

Gracias @n1bor.

**Closed** 2018-05-30 11:38 UTC
