### ISSUE TITLE
Crash which closed/spent all incoming channels

### ISSUE THREAD

**Issue by kravens** [ACINQ/eclair#794] opened 2018-12-27 17:23 UTC
Software + OS crash occured, after reboot all channels funded by other people/nodes have disappeared from the Local Channel tab. And a RBF transaction seems to have been broadcast on the associated channel funds around the same time.

Expected all self funded and other channels to be found after reboot.

But the channels funded by others with my node somehow have failed and seem to have been spent, all 3 channels from different funders (unlikely to coincidentally force close simultaneous).
This is one of the suddenly closed channels tx: https://blockstream.info/address/bc1q0y5kmpfenzed3gwvcgr4jv5fcqhmpcvvdxcnumtxzd6e0vz0vwmsqypcl9 

Not sure how to reproduce this, never had this issue before... hope there is some info in the eclair.log below.

Eclair v0.2-beta8

Windows 10, Version 10.0.17134 Build 17134

See full log: 
> 2018-12-27 17:12:57,506 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=8711500060c0000 (awaiting=22 stash.nodes=0 stash.updates=31)
2018-12-27 17:12:57,506 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=8711500060c0000 tx=44a3e3d36c653ee198f4e973933633038517f96cefa7d7673ccd330dcf39d7cb (funding tx already spent)
2018-12-27 17:12:57,742 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=872700002bb0001 (awaiting=21 stash.nodes=0 stash.updates=30)
2018-12-27 17:12:57,742 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=872700002bb0001 tx=785b95e1fbf8b78cdd2c0dec47d3aabd120416ad792523c633bf701b92ce10cd (funding tx already spent)
2018-12-27 17:12:57,743 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=871c80006be0000 (awaiting=20 stash.nodes=0 stash.updates=29)
2018-12-27 17:12:57,743 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=871c80006be0000 tx=34f76eff6b7507988b5a8971d9cfc0dbf3678bf991dd5451413272d57568a61c (funding tx already spent)
2018-12-27 17:12:57,743 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=872dd0002540000 (awaiting=19 stash.nodes=0 stash.updates=28)
2018-12-27 17:12:57,743 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=872dd0002540000 tx=76952673001fdf60ee23b2341d667f53e7237f71cae61cb2a2d6440b2f4e4e63 (funding tx already spent)
2018-12-27 17:12:57,743 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=8724b0003cd0001 (awaiting=18 stash.nodes=0 stash.updates=27)
2018-12-27 17:12:57,743 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=8724b0003cd0001 tx=f32385236a850363bdf837bdbed228e4954b8c8d68438522ea7765e32ae48634 (funding tx already spent)
2018-12-27 17:12:57,743 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=8736900087e0001 (awaiting=17 stash.nodes=0 stash.updates=26)
2018-12-27 17:12:57,743 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=8736900087e0001 tx=ffa37622e12d1192dbb17e481cb0ddf23454e05be268d1d7e7c28b3f59126dd8 (funding tx already spent)
2018-12-27 17:12:57,746 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=874780008db0001 (awaiting=16 stash.nodes=0 stash.updates=25)
2018-12-27 17:12:57,746 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=874780008db0001 tx=1fd1646b248c886c1cc7c0255c4132ccfd35eae91a2babbd28b832f3c16da22c (funding tx already spent)
2018-12-27 17:12:57,746 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=877930002950001 (awaiting=15 stash.nodes=0 stash.updates=23)
2018-12-27 17:12:57,746 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=877930002950001 tx=0d6953e52a09ec9c0b59db63a65c204c4795c225b27d95f6c2f873f1af17c51c (funding tx already spent)
2018-12-27 17:12:57,747 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=879240005fc0001 (awaiting=14 stash.nodes=0 stash.updates=21)
2018-12-27 17:12:57,747 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=879240005fc0001 tx=f63a1be23d66f470dcb7caa0509148f493bb154b8569669c13d450beea1bef4d (funding tx already spent)
2018-12-27 17:12:57,747 WARN  fr.acinq.eclair.io.Peer  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - peer sent us too many channel announcements with funding tx already spent (count=11), ignoring network announcements for 5 minutes
2018-12-27 17:12:57,747 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=878b400067e0000 (awaiting=13 stash.nodes=0 stash.updates=19)
2018-12-27 17:12:57,747 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=878b400067e0000 tx=99b3084bea0bdf22ac1f2332a0b4c4a8b23827b1e69264746b63e4098f473490 (funding tx already spent)
2018-12-27 17:12:57,747 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=8792a0000db0001 (awaiting=12 stash.nodes=0 stash.updates=17)
2018-12-27 17:12:57,747 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=8792a0000db0001 tx=0f61c8cd848b8c576278ae8b1cb6f280efcea7d2e5600775cc14da69f4e60312 (funding tx already spent)
2018-12-27 17:12:57,747 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=879670002860001 (awaiting=11 stash.nodes=0 stash.updates=15)
2018-12-27 17:12:57,747 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=879670002860001 tx=bb51e5fd05ac62219fc62b69c96bfff6646d984cbdd5eba045dda11e457dfe64 (funding tx already spent)
2018-12-27 17:12:57,747 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=879240006650000 (awaiting=10 stash.nodes=0 stash.updates=13)
2018-12-27 17:12:57,747 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=879240006650000 tx=6ad02acd7c5c39a3d769bcf6be58023de00af4bf1a82f8f7535dc99baa5d3703 (funding tx already spent)
2018-12-27 17:12:57,747 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=87949000bdd0001 (awaiting=9 stash.nodes=0 stash.updates=12)
2018-12-27 17:12:57,747 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=87949000bdd0001 tx=222d87a1b4d11317470ae08355ee044172d35148403b1efbc5d6f00675c84d33 (funding tx already spent)
2018-12-27 17:12:57,747 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=879570005f30001 (awaiting=8 stash.nodes=0 stash.updates=11)
2018-12-27 17:12:57,747 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=879570005f30001 tx=01a1149abf5ffb90866d2b2137ff5fc4d07457aabb06f4bf79d0a5d2c123d415 (funding tx already spent)
2018-12-27 17:12:57,748 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=8792a0000f70001 (awaiting=7 stash.nodes=0 stash.updates=10)
2018-12-27 17:12:57,748 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=8792a0000f70001 tx=17724f00bb2cc1b3f80225cb3a7f8f81220171e31b47cb635009fabdf1bf063a (funding tx already spent)
2018-12-27 17:12:57,748 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=8792a0000f60001 (awaiting=6 stash.nodes=0 stash.updates=8)
2018-12-27 17:12:57,748 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=8792a0000f60001 tx=0561bde7c3dcd714b760a53c2a2cd7bd17579e9f9b3bfe9ce99c5a90baadde88 (funding tx already spent)
2018-12-27 17:12:57,748 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=879730000fc0000 (awaiting=5 stash.nodes=0 stash.updates=6)
2018-12-27 17:12:57,748 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=879730000fc0000 tx=5e1b0e56f28f7982abea0665d4981130d8f672ba8dd9a7c1471a53c44b11ef49 (funding tx already spent)
2018-12-27 17:12:57,748 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=87949000bde0000 (awaiting=4 stash.nodes=0 stash.updates=5)
2018-12-27 17:12:57,748 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=87949000bde0000 tx=66d0b15814286fba13d5c833bbcd6b3bbc8c32da673be0b90b27aa1e009aff49 (funding tx already spent)
2018-12-27 17:12:57,748 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=8797b00035b0000 (awaiting=3 stash.nodes=0 stash.updates=4)
2018-12-27 17:12:57,748 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=8797b00035b0000 tx=2c517917c633cd1f061ccc83cf095c20bc0545fa6c1e7988e280fdaa3d99c0a3 (funding tx already spent)
2018-12-27 17:12:57,748 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=8796d0004c80001 (awaiting=2 stash.nodes=0 stash.updates=3)
2018-12-27 17:12:57,748 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=8796d0004c80001 tx=7b2f797c98f0deded4c8755b3221a19d95aae46ef47d91213aed7aafd21024e3 (funding tx already spent)
2018-12-27 17:12:57,748 INFO  f.a.eclair.router.Router  - got validation result for shortChannelId=8763c0004ea0001 (awaiting=1 stash.nodes=0 stash.updates=2)
2018-12-27 17:12:57,748 WARN  f.a.eclair.router.Router  - ignoring shortChannelId=8763c0004ea0001 tx=b961539569f9418490fb76db09e06edff88a4b0f5a13d39c7ef844a014cef64e (funding tx already spent)
2018-12-27 17:12:57,934 INFO  fr.acinq.eclair.io.Peer  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - resuming processing of network announcements for peer
2018-12-27 17:13:53,594 INFO  fr.acinq.eclair.io.Peer  n:02da65c851216c09066b2ece048af560dcf5524fc96bf6e22fc5d872c42740fa4c - sent announcements to 02da65c851216c09066b2ece048af560dcf5524fc96bf6e22fc5d872c42740fa4c: channels=0 updates=7 nodes=0
2018-12-27 17:13:53,594 INFO  fr.acinq.eclair.io.Peer  n:02064f740ee3dda8d58ad6300fecad02c87496050fcaf512a0bbe70950a3f07d1d - sent announcements to 02064f740ee3dda8d58ad6300fecad02c87496050fcaf512a0bbe70950a3f07d1d: channels=0 updates=4 nodes=0
2018-12-27 17:13:53,594 INFO  fr.acinq.eclair.io.Peer  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - sent announcements to 0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a: channels=0 updates=8 nodes=0
2018-12-27 17:13:53,594 INFO  fr.acinq.eclair.io.Peer  n:02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b - sent announcements to 02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b: channels=0 updates=2 nodes=0
2018-12-27 17:13:53,594 INFO  fr.acinq.eclair.io.Peer  n:026d92e8c39aa2c08d51b56647508be2c8de32e71a69ca2f3f5880c46c5d8e0ea7 - sent announcements to 026d92e8c39aa2c08d51b56647508be2c8de32e71a69ca2f3f5880c46c5d8e0ea7: channels=0 updates=8 nodes=0
2018-12-27 17:13:53,594 INFO  fr.acinq.eclair.io.Peer  n:03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f - sent announcements to 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f: channels=0 updates=6 nodes=0
2018-12-27 17:13:53,594 INFO  fr.acinq.eclair.io.Peer  n:03e265de1d313ef2b5dfff2f3677980114d28ae66ecc52d7ff855217f3fc7b51fc - sent announcements to 03e265de1d313ef2b5dfff2f3677980114d28ae66ecc52d7ff855217f3fc7b51fc: channels=0 updates=8 nodes=0
2018-12-27 17:13:53,594 INFO  fr.acinq.eclair.io.Peer  n:034df87aa03be1cdb60d8acfbe69d5cfde480c0d53f853f73d2243d3b2464857cb - sent announcements to 034df87aa03be1cdb60d8acfbe69d5cfde480c0d53f853f73d2243d3b2464857cb: channels=0 updates=8 nodes=0
2018-12-27 17:13:53,594 INFO  fr.acinq.eclair.io.Peer  n:03717261ceeb64c5170ff5dd765ff070f6cd69616da8b0488f4ca0d6e4978778c7 - sent announcements to 03717261ceeb64c5170ff5dd765ff070f6cd69616da8b0488f4ca0d6e4978778c7: channels=0 updates=7 nodes=0
2018-12-27 17:13:53,594 INFO  fr.acinq.eclair.io.Peer  n:03321fab5e3db6c378e23e9cceb522325dc4f6b0c68819944569128d34cba9cca3 - sent announcements to 03321fab5e3db6c378e23e9cceb522325dc4f6b0c68819944569128d34cba9cca3: channels=0 updates=8 nodes=0
2018-12-27 17:13:53,857 INFO  f.a.eclair.Diagnostics  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a c:0000000000000000000000000000000000000000000000000000000000000000 - IN msg=Error(0000000000000000000000000000000000000000000000000000000000000000,62616420616e6e6f756e63656d656e7420736967212062696e3d5375636365737366756c28426974566563746f72283130343020626974732c20232d313633363533323435372929)
2018-12-27 17:13:53,857 ERROR fr.acinq.eclair.io.Peer  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - connection-level error, failing all channels! reason=bad announcement sig! bin=Successful(BitVector(1040 bits, #-1636532457))
2018-12-27 17:13:53,857 INFO  fr.acinq.eclair.io.Peer  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - lost connection to 0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a
2018-12-27 17:13:55,769 INFO  f.acinq.eclair.io.Server  - connected to /185.217.69.171:65203
2018-12-27 17:13:55,997 INFO  f.a.e.io.Authenticator  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - connection authenticated with 0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a@185.217.69.171:65203 direction=incoming
2018-12-27 17:13:55,997 INFO  fr.acinq.eclair.io.Peer  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - 0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a has features: initialRoutingSync=true channelRangeQueriesOptional=true channelRangeQueriesMandatory=false
2018-12-27 17:13:55,997 INFO  fr.acinq.eclair.io.Peer  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - 0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a has set initial routing sync and support channel range queries, we do nothing (they will send us a query)
2018-12-27 17:13:55,997 INFO  f.a.eclair.router.Router  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - sending query_channel_range=QueryChannelRange(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,0,2147483647)
2018-12-27 17:13:56,215 INFO  fr.acinq.eclair.io.Peer  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - setting up gossipTimestampFilter=GossipTimestampFilter(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,0,2147483647)
2018-12-27 17:13:56,215 INFO  f.a.eclair.router.Router  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - received query_channel_range=QueryChannelRange(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,0,2147483647)
2018-12-27 17:13:56,236 INFO  f.a.eclair.router.Router  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - sending back reply_channel_range with 16064 items for range=(0, 2147483647)
2018-12-27 17:13:56,755 INFO  f.a.eclair.router.Router  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - received reply_channel_range, we're missing 1 channel announcements/updates, format=0 useGzip=false
2018-12-27 17:13:56,983 INFO  f.a.eclair.router.Router  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - received reply_channel_range, we're missing 9 channel announcements/updates, format=0 useGzip=false
2018-12-27 17:13:56,985 INFO  f.a.eclair.router.Router  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - received reply_channel_range, we're missing 29 channel announcements/updates, format=0 useGzip=false
2018-12-27 17:13:57,189 INFO  f.a.eclair.router.Router  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - received query_short_channel_ids for 15 channel announcements, useGzip=false
2018-12-27 17:13:57,189 INFO  f.a.eclair.router.Router  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - received reply_short_channel_ids_end=ReplyShortChannelIdsEnd(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,1)
2018-12-27 17:13:57,189 INFO  f.a.eclair.router.Router  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - asking 0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a for the next slice of short_channel_ids
2018-12-27 17:13:57,194 INFO  f.a.eclair.router.Router  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - validating shortChannelId=842290004320000
2018-12-27 17:24:17,433 INFO  a.e.slf4j.Slf4jLogger  - Slf4jLogger started
2018-12-27 17:24:17,449 INFO  fr.acinq.eclair.Setup  - hello!

**Comment by sstone** [comment] 2018-12-28 12:19
Can you give us more details on this OS/Software crash ? 
Is it possible the share your logs (using pastebin for example) ? Where all this channels open to the same node or to different nodes ?
To search quickly in the logs you can ignore Router related messages and look for lines tagged with `ERROR`.

**Comment by kravens** [comment] 2018-12-29 01:34
There was no memory dump or log of the explorer.exe crash sadly.
I was also connected to ''POTTERNODE", and there seems to have been a conflict between our nodes for some reason that took down with it another open channel from "LightningPowerUsers". 

Misbehaving channel: https://1ml.com/channel/600987558195757057 with remote Node: https://1ml.com/node/0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a 

This error seems to come up often in my Eclair.log:
> 2018-12-27 17:12:54,047 INFO  f.a.eclair.Diagnostics  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a c:0000000000000000000000000000000000000000000000000000000000000000 - IN msg=Error(0000000000000000000000000000000000000000000000000000000000000000,62616420616e6e6f756e63656d656e7420736967212062696e3d5375636365737366756c28426974566563746f72283130343020626974732c20232d3836383531323638342929)
2018-12-27 17:12:54,047 ERROR fr.acinq.eclair.io.Peer  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - connection-level error, failing all channels! reason=bad announcement sig! bin=Successful(BitVector(1040 bits, #-868512684))
2018-12-27 17:12:54,047 INFO  fr.acinq.eclair.io.Peer  n:0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a - lost connection to 0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a

More after the reboot:
> https://pastebin.com/2AVJ6Rns

History of my Eclair node lightning channels: https://1ml.com/node/027ba5217fecd12ebb621e51b88b8c9640cce659bd894f4c8e820e09173826fca2

**Comment by sstone** [comment] 2019-01-04 12:03
I could not reproduce the issue with LightningPowerUsers,  and cannot connect to 0245cd8164efd4f0d02014e00a7606aeffa5016e8a9c72c78edeb7e3da731f720a, but the `bad announcement` error that you see is very likely because you were connected to an old eclair node that has a bug (which was fixed in beta8) in how it handles `channel_update` messages (see #751). It will not close all channels, but only the ones with this specific node. And you should have received your funds back in your wallet on all the channels that were closed by now.

**Comment by kravens** [comment] 2019-01-04 18:59
Thanks for looking into it, I indeed got all the funds back after the channels closed. 
So most likely the other node used an old eclair version, since then I have not had any crashes or ERROR logs.

**Closed** 2019-01-09 17:58 UTC
