### ISSUE TITLE
Open channel fails with "Error: Please enter the wallet passphrase with walletpassphrase first. (code: -13)"  How do I fix this? How do I submit the wallet passphrase in the "Open new channel" dialogue? Bitcoin Core version v0.17.1 (64-bit) and Eclair v0_2-beta 8 and everything worked until I tried to open a new channel.

### ISSUE THREAD

**Issue by Molde1964** [ACINQ/eclair#803] opened 2019-01-04 09:01 UTC

**Comment by sstone** [comment] 2019-01-04 09:52
Duplicate of #140 and #607

**Closed by sstone** 2019-01-04 09:52 UTC
