### ISSUE TITLE
Double fee payment

### ISSUE THREAD

**Issue by coinsmith** [ACINQ/eclair#427] opened 2018-02-03 21:20 UTC
Not sure if I did something wrong, but here's the situation on testnet.

Bitcoin testnet input of 0.1 Bitcoin on the android lightning testnet wallet.
I opened a payment channel for 150000 sats with a lightning node. I immediately pay 27072 sats fee. This amount + 150000 disappears from my balance. I now have an open channel for 150000 sats. I don't see my channel on explorer.acinq.co , but wait a bit. Nothing changes. There are on chain confirmations of the open channel in the testnet explorer. 
I decide to close the channel. Now, I get 123888 sats returned, so it seems I've paid an on chain fee twice. My final balance is now 0.9946816. I would think this is a weird issue, paying an on chain fee twice.

This is my first test, so if I overlooked something, please correct me and remove this issue. Thanks.

**Comment by pm47** [comment] 2018-02-05 13:06
Opening and closing a channel each require making an on-chain transaction, which requires paying fees to the bitcoin network. In other words what you are observing is the expected behavior.

If you want to make the best of Lightning, you should leave channels open as long as possible and use them to make payments. Channels on Lightning can live indefinitely, the longer they exist the more you can average down the cost of opening and closing them.

Channels created with the mobile app are not announced on the network, that's why you don't see them on the explorer. They don't need to because the app is send-only for now.

I'm closing this I don't see any bug.

**Closed by pm47** 2018-02-05 13:06 UTC

**Comment by coinsmith** [comment] 2018-02-05 14:30
Thanks!
