### ISSUE TITLE
Channel hangs on WAIT_FOR_ACCEPT_CHANNEL state

### ISSUE THREAD

**Issue by Zulfus** [ACINQ/eclair#437] opened 2018-02-13 20:01 UTC
I managed to open an initial channel with the node "endurance" on testnet, however attempting to open further channels remain in the WAIT_FOR_ACCEPT_CHANNEL state. The result of "eclair-cli channels" returns: 

> [
>   {
>     "nodeId": "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134",
>     "channelId": "1f957b3513dda9f84bf2195b80a52803c509958b181d6191f32ee14edafabb84",
>     "state": "NORMAL"
>   },
>   {
>     "nodeId": "02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b855",
>     "channelId": "2af88e5e7ca7c6aa0f16cb3b5dba943ec2672a7420b6f8af03d183865602a885",
>     "state": "WAIT_FOR_ACCEPT_CHANNEL"
>   },
>   {
>     "nodeId": "02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b855",
>     "channelId": "af218d0404884d4d782576a1d3c678372f28c8b768d06378ee7985e598a512eb",
>     "state": "WAIT_FOR_ACCEPT_CHANNEL"
>   }
> ]

Running tail on the log after trying to open a channel gives the following: 

> 2018-02-13 19:48:06,076 INFO  fr.acinq.eclair.channel.Channel akka://default/use                                 r/$h/switchboard/peer-02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35                                 e834b855/$b 9369eb5bab96531b2118abdcc8b3c7aab91c26cd34bffa1b074ae74a661011ab - s                                 hutting down
> 2018-02-13 19:48:06,116 INFO  fr.acinq.eclair.io.Peer akka://default/user/$h/swi                                 tchboard/peer-02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b855                                   - channel closed: channelId=TemporaryChannelId(9369eb5bab96531b2118abdcc8b3c7a                                 ab91c26cd34bffa1b074ae74a661011ab)
> 2018-02-13 19:48:06,117 INFO  fr.acinq.eclair.io.Peer akka://default/user/$h/swi                                 tchboard/peer-02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b855                                   - that was the last open channel, closing the connection
> 2018-02-13 19:48:06,122 INFO  fr.acinq.eclair.io.Peer akka://default/user/$h/swi                                 tchboard/peer-02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b855                                   - lost connection to 02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd3                                 5e834b855
> 2018-02-13 19:49:22,381 INFO  fr.acinq.eclair.io.Client akka://default/user/$h/s                                 witchboard/peer-02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b8                                 55/$c  - connecting to pubkey=02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4                                 111bbd35e834b855 host=109.99.154.45 port=9735
> 2018-02-13 19:49:22,528 INFO  fr.acinq.eclair.io.Client akka://default/user/$h/s                                 witchboard/peer-02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b8                                 55/$c  - connected to pubkey=02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec41                                 11bbd35e834b855 host=109.99.154.45 port=9735
> 2018-02-13 19:49:22,713 INFO  fr.acinq.eclair.io.Authenticator akka://default/us                                 er/$g/authenticator  - connection authenticated with 02575c8b82dcb4b2936ef52326f                                 a952127f9e85748b50abec4111bbd35e834b855@109.99.154.45:9735 direction=outgoing
> 2018-02-13 19:49:23,292 INFO  fr.acinq.eclair.io.Peer akka://default/user/$h/swi                                 tchboard/peer-02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b855                                   - 02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b855 has featu                                 res: initialRoutingSync=true
> 2018-02-13 19:49:39,177 INFO  fr.acinq.eclair.io.Peer akka://default/user/$h/swi                                 tchboard/peer-02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b855                                   - requesting a new channel to 02575c8b82dcb4b2936ef52326fa952127f9e85748b50abe                                 c4111bbd35e834b855 with fundingSatoshis=Satoshi(1000000) and pushMsat=MilliSatos                                 hi(0)

I have attempted opening numerous channels with many different nodes, they all connect fine, but all remain in this state when trying to open a channel. 

I'm also unable to make payments to y'alls or starblocks, or other lightning nodes, however assumed this may be a route issue? Hence trying to open more than 1 channel.

I have been following this guide: https://medium.com/@stadicus/noobs-guide-to-%EF%B8%8F-lightning%EF%B8%8F-on-a-raspberry-pi-f0ab7525586e

and only send & now open commands seem to be failing.

**Comment by sstone** [comment] 2018-02-15 10:21
I have not been able to reproduce the problem: I can open a channel to 02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b855. I have the same setup (one channel to 0393..., another one to 02575...) and can pay starblocks. 

A channel stuck in WAIT_FOR_ACCEPT_CHANNEL  means that we could establish an encrypted and authenticated connection to the remote peer, send an `open_channel` message, this connection is still open but they have not replied.  It is hard to know why, and we don't have yet implemented policies for dealing with unresponsive peers. In this case the simplest option is to close the channel (you cannot loose funds) and try again later (possibly with another node).  

Support questions are better asked on https://gitter.im/ACINQ/eclair (though it's not always easy to choose between bug report and support question).

**Comment by pm47** [comment] 2018-03-13 14:26
I'm closing this as duplicate of #454 (issue will be fixed in #453).

**Closed by pm47** 2018-03-13 14:26 UTC
Labels: duplicate
