### ISSUE TITLE
Add cancelinvoice API 

### ISSUE THREAD

**Issue by Kukks** [ACINQ/eclair#1916] opened 2021-08-19 08:48 UTC
A cancel invoice API would be great to be able to reject payments to invoices you no longer want paid.

**Comment by t-bast** [comment] 2021-08-23 07:59
This is a duplicate of #1510

**Closed by t-bast** 2021-08-23 07:59 UTC

**Comment by btcontract** [comment] 2021-08-23 08:04
I'm not sure it's a duplicate, what's desired here is to delete a not yet expired invoice.

**Comment by t-bast** [comment] 2021-08-23 08:23
IMO a future `deleteinvoice` RPC should allow deleting non-expired invoices as well. The only case where it should reject the delete request is if the invoice has been paid.
