### ISSUE TITLE
Invalid Signature in FUNDING_SIGNED

### ISSUE THREAD

**Issue by matsjj** [ACINQ/eclair#234] opened 2017-11-24 17:28 UTC
It seems to me that 0.3-alpha5 produces a signature in FUNDING_SIGNED message based on an invalid Transaction. More specifically, it adds outputs for both parties, but doesn't trim them before creating the signature. In my case, this leads to signing 

```
Transaction(2,List(TxIn(OutPoint(72de043a596e3e3cf32be9bee7e11c821493df39b809df035bdc38011a658867,0),,2154763758,ScriptWitness(List()))),List(TxOut(Satoshi(0),0014d56c70bad7311384670fc7b297d25e1aac0072e3), TxOut(Satoshi(92760),00202b7c43dafd7537b425a4a292cb7a9d91823641ce6be21326dfb65bbedf50cd5d)),537113288)
```

It seems to me that this is always the case when pushMsat is < dustLimit.

**Comment by pm47** [comment] 2017-11-24 18:15
Hi Mats, nice to hear from you :-)

I will investigate, but I can't see any obvious issue here, what `dustLimit` value are you using?

https://github.com/ACINQ/eclair/blob/a97fa39fef96964367d71009876f56b369039f64/eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala#L154-L155

Any chance you can try to reproduce against master? The version you are using was pre-interop tests so I'm pretty sure that kind of bugs would have been detected, because `pushMsat` < `dustLimit` is the default.

Thanks!

**Comment by btcontract** [comment] 2017-11-24 18:20
Not sure if this is related but one of commits in my PR failed with `17:36:06.970 ERROR akka://test/user/$$r - their FundingSigned message contains an invalid signature java.lang.RuntimeException: invalid signature` which is strange since I've changed nothing in code which could cause that.

**Comment by sstone** [comment] 2017-11-24 18:45
@btcontract  I believe this is expected, this particular test checks that we send an error when we receive an invalid signature. Your build fails in the OfflineStateSpec.

@matsjj can you share the open and accept messages ? the trimming code was already in 0.2-alpha5 so it might be an encoding issue.

Thanks!

**Comment by matsjj** [comment] 2017-11-25 08:31
Ah, indeed, I was just silly with my serialisation. :-)

Maybe it's worth asserting some sane values (in all implementations), like 546 as dustLimit. Thanks for the help!

**Comment by sstone** [comment] 2017-11-25 14:01
No problem!

**Comment by pm47** [comment] 2017-11-25 16:08
@matsjj I think the reason why the spec gives a lot of freedom on this is because you can only hurt yourself: each party chooses its own dust limit. The only problem is when negotiating the closing tx, which is described [here](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#rationale).

@sstone I'm reopening this because we should at least make sure our own parameter is above 546 when reading the conf, otherwise users can put their funds at risk.

This made me also realize we are missing some validation checks on parameters, creating a new issue for that.

**Closed** 2017-11-29 17:18 UTC
