### ISSUE TITLE
Display bugs in GUI Activity tab

### ISSUE THREAD

**Issue by windsok** [ACINQ/eclair#115] opened 2017-07-23 17:23 UTC
When testing receiving some transactions with eclair javafx GUI, noticed a couple of display bugs in the "Received" section of the "Activity" tab.

1) For every new transaction received, the date for all prior transactions is updated to the date of the last transaction received.

2) Upon receiving my 4th transaction, all the transactions values were duplicated into new rows in the table.

State with 3 transactions recieved:
<img width="968" alt="eclair1" src="https://user-images.githubusercontent.com/8359865/28501462-fabf2e1a-6f90-11e7-971d-56802a367e40.png">

State after 4th transaction:
<img width="953" alt="eclair2" src="https://user-images.githubusercontent.com/8359865/28501463-00a8c246-6f91-11e7-8f0e-989c3e0a789e.png">

**Comment by dpad85** [comment] 2017-07-26 17:23
The problem with the date is fixed, however I could not reproduce the bug with the duplicated rows. If it happens again, could you join the logs (which you can find in the eclair datadir, by default `~/.eclair`) ?
Thanks!

**Comment by dpad85** [comment] 2017-08-23 12:18
I still could not reproduce the duplicated row issue. Let's close this ticket and please reopen it if needed.

**Closed by dpad85** 2017-08-23 12:18 UTC
