### ISSUE TITLE
Channels getting closed due to fee rate differences

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#640] opened 2018-06-22 09:41 UTC
Know this is a known issue - but is still and issue! Log below of a burst of closes I got.
Errors from Peers:
`
eclairdebug.2018-06-19.log:15:39:42.939 remoteFeeratePerKw=13362 localFeeratePerKw=1891' 
eclairdebug.2018-06-21.log:13:49:37.221 remoteFeeratePerKw=12147 localFeeratePerKw=500' 
`
Errors we sent:
`
eclairdebug.2018-06-17.log:04:59:36.356 remoteFeeratePerKw=3548 localFeeratePerKw=500
eclairdebug.2018-06-19.log:15:39:37.033 remoteFeeratePerKw=1888 localFeeratePerKw=13362
eclairdebug.2018-06-19.log:15:39:37.033 remoteFeeratePerKw=1888 localFeeratePerKw=13362
eclairdebug.2018-06-19.log:15:39:39.071 remoteFeeratePerKw=1888 localFeeratePerKw=13362
eclairdebug.2018-06-20.log:18:39:36.320 remoteFeeratePerKw=768 localFeeratePerKw=37364
eclairdebug.2018-06-21.log:06:39:36.312 remoteFeeratePerKw=41159 localFeeratePerKw=5567
eclairdebug.2018-06-21.log:06:39:36.824 remoteFeeratePerKw=41000 localFeeratePerKw=5567
eclairdebug.2018-06-21.log:06:39:36.824 remoteFeeratePerKw=41159 localFeeratePerKw=5567
eclairdebug.2018-06-21.log:06:39:36.945 remoteFeeratePerKw=41159 localFeeratePerKw=5567
eclairdebug.2018-06-21.log:06:39:37.218 remoteFeeratePerKw=41159 localFeeratePerKw=5567
eclairdebug.2018-06-21.log:09:09:36.312 remoteFeeratePerKw=35500 localFeeratePerKw=924
eclairdebug.2018-06-21.log:12:27:24.182 remoteFeeratePerKw=41000 localFeeratePerKw=500
eclairdebug.2018-06-21.log:13:49:36.579 remoteFeeratePerKw=500 localFeeratePerKw=12147
eclairdebug.2018-06-21.log:16:39:36.323 remoteFeeratePerKw=7489 localFeeratePerKw=1001
eclairdebug.2018-06-21.log:20:39:36.329 remoteFeeratePerKw=25317 localFeeratePerKw=3587
eclairdebug.2018-06-21.log:21:19:50.392 remoteFeeratePerKw=37482 localFeeratePerKw=3601
`

**Comment by mautematico** [comment] 2018-06-23 07:59
use

`max-feerate-mismatch = 100000`

To essentially remove the errors from peers.

**Comment by btcontract** [comment] 2018-06-23 08:58
Actually `max-feerate-mismatch = 2` would suffice, it's nonlinear. If only all the peers had the same settings.

**Comment by pm47** [comment] 2018-06-24 13:10
Yes, `max-feerate-mismatch` is the correct answer

> If only all the peers had the same settings.

It is actually a bit more complicated: fee estimation is really tricky, and two bitcoin-core of the same version may give very different estimates from time to time (it depends on the mempool among other things). We have seen two instances of eclair, or two instances of c-lightning disagree while they had the exact same settings, just because they were connected to different bitcoin-cores.

**Comment by pm47** [comment] 2018-06-24 13:11
@sstone we may need to change the default value and be a bit more lax

**Comment by n1bor** [comment] 2018-07-03 21:17
What are the risk here?
Is it just that we might end up paying too much to close channel - which is mainly an issue if we are funder.
The risks when it is too low is just that we might lock up funds until the fees reduce if we have to force close the channel? Which is not too bad. If funds are locked up for a few days or weeks not really an issue. And locks up both sides funds so if fee rate is too low more incentive for everyone to negotiate a mutual close.

So should our logic not be asymmetric - so if we are a funder we do care if they are too high if not don't care that much? Also think logic should be bit dependent on age of channel. If it has been open for many weeks then there is an element of trust built into it so we should again be more lenient. Or could this all be gamed?

**Comment by n1bor** [comment] 2018-07-10 20:30
Lost a load of channels today due to other side closing:

`
13:49:50.025 ERROR akka://default/user/$h/switchboard/peer-038fe3c921a6bc389d28fc6a47e131b07adfb36450bfc1553d6445b182eb84c9bd/$a fr.acinq.eclair.channel.Channel - peer sent error: ascii='update_fee 9476 outside range 875-7825' bin=7570646174655f6665652039343736206f7574736964652072616e6765203837352d37383235
13:49:53.534 ERROR akka://default/user/$h/switchboard/peer-027fe40fda644dbbce9b51fc7cff5809586d02bfc7c308d54a80002989c14f40de/$a fr.acinq.eclair.channel.Channel - peer sent error: ascii='update_fee 9476 outside range 875-7825' bin=7570646174655f6665652039343736206f7574736964652072616e6765203837352d37383235
13:49:53.538 ERROR akka://default/user/$h/switchboard/peer-031656e93300e7d51f9dcb2780d63b44cb96c5d6af2cec2196de450ad0688fcb80/$a fr.acinq.eclair.channel.Channel - peer sent error: ascii='update_fee 9476 outside range 875-7825' bin=7570646174655f6665652039343736206f7574736964652072616e6765203837352d37383235
13:49:53.539 ERROR akka://default/user/$h/switchboard/peer-03473ec133c70c05db8d1abaa272449b0cfd3d38e1978bfe1e7765d1913b7e7c51/$a fr.acinq.eclair.channel.Channel - peer sent error: ascii='update_fee 9476 outside range 875-7825' bin=7570646174655f6665652039343736206f7574736964652072616e6765203837352d37383235
13:49:54.195 ERROR akka://default/user/$h/switchboard/peer-038a834010a354a4f8ec8438bd50b712e13606fccffb9280af8125e2c9e039ffe7/$a fr.acinq.eclair.channel.Channel - peer sent error: ascii='update_fee 9476 outside range 875-7825' bin=7570646174655f6665652039343736206f7574736964652072616e6765203837352d37383235
13:49:54.346 ERROR akka://default/user/$h/switchboard/peer-038fe3c921a6bc389d28fc6a47e131b07adfb36450bfc1553d6445b182eb84c9bd/$a fr.acinq.eclair.channel.Channel - peer sent error: ascii='update_fee 9476 outside range 875-7825' bin=7570646174655f6665652039343736206f7574736964652072616e6765203837352d37383235
13:49:54.803 ERROR akka://default/user/$h/switchboard/peer-031656e93300e7d51f9dcb2780d63b44cb96c5d6af2cec2196de450ad0688fcb80/$a fr.acinq.eclair.channel.Channel - peer sent error: ascii='update_fee 9476 outside range 875-7825' bin=7570646174655f6665652039343736206f7574736964652072616e6765203837352d37383235
13:49:55.045 ERROR akka://default/user/$h/switchboard/peer-03473ec133c70c05db8d1abaa272449b0cfd3d38e1978bfe1e7765d1913b7e7c51/$a fr.acinq.eclair.channel.Channel - peer sent error: ascii='update_fee 9476 outside range 875-7825' bin=7570646174655f6665652039343736206f7574736964652072616e6765203837352d37383235
13:49:55.490 ERROR akka://default/user/$h/switchboard/peer-02a456b816697c6b8407ee2176475d74b790a96143bc30e896e8bf7a8852a8b637/$a fr.acinq.eclair.channel.Channel - peer sent error: ascii='update_fee 9476 outside range 875-7825' bin=7570646174655f6665652039343736206f7574736964652072616e6765203837352d37383235
13:49:55.840 ERROR akka://default/user/$h/switchboard/peer-027fe40fda644dbbce9b51fc7cff5809586d02bfc7c308d54a80002989c14f40de/$a fr.acinq.eclair.channel.Channel - peer sent error: ascii='update_fee 9476 outside range 875-7825' bin=7570646174655f6665652039343736206f7574736964652072616e6765203837352d37383235
13:50:15.856 ERROR akka://default/user/$h/switchboard/peer-038a834010a354a4f8ec8438bd50b712e13606fccffb9280af8125e2c9e039ffe7/$a fr.acinq.eclair.channel.Channel - peer sent error: ascii='update_fee 9476 outside range 875-7825' bin=7570646174655f6665652039343736206f7574736964652072616e6765203837352d37383235
`
due to us spiking from 1497->9476
`
13:39:44.390 INFO   fr.acinq.eclair.Setup - current feeratesPerKB=FeeratesPerKB(48475,5991,3825,2000,2000,2000) feeratesPerKw=FeeratesPerKw(12118,1497,956,500,500,500)
13:49:44.387 INFO   fr.acinq.eclair.Setup - current feeratesPerKB=FeeratesPerKB(48348,37907,3825,2000,2000,2000) feeratesPerKw=FeeratesPerKw(12087,9476,956,500,500,500)
13:59:44.420 INFO   fr.acinq.eclair.Setup - current feeratesPerKB=FeeratesPerKB(48348,37907,3825,2000,2000,2000) feeratesPerKw=FeeratesPerKw(12087,9476,956,500,500,500)
14:09:44.595 INFO   fr.acinq.eclair.Setup - current feeratesPerKB=FeeratesPerKB(48335,38034,5409,2000,2000,2000) feeratesPerKw=FeeratesPerKw(12083,9508,1352,500,500,500)
14:19:44.377 INFO   fr.acinq.eclair.Setup - current feeratesPerKB=FeeratesPerKB(48345,14992,6267,2000,2000,2000) feeratesPerKw=FeeratesPerKw(12086,3748,1566,500,500,500)
14:29:44.391 INFO   fr.acinq.eclair.Setup - current feeratesPerKB=FeeratesPerKB(50149,12981,6260,2000,2000,2000) feeratesPerKw=FeeratesPerKw(12537,3245,1565,500,500,500)
14:39:44.417 INFO   fr.acinq.eclair.Setup - current feeratesPerKB=FeeratesPerKB(50156,12991,6260,2000,2000,2000) feeratesPerKw=FeeratesPerKw(12539,3247,1565,500,500,500)
`

Why do we use the 2 block estimate that is bound to be volatile rather than 6, 12 or more?
Can this be changed in the protocol? Just the longer the period the less volatile the numbers are.

Computed quick stats from june/july and get:


  | 1 | 2 | 6 | 12 | 36 | 72
-- | -- | -- | -- | -- | -- | --
Mean | 34,655 | 6,447 | 3,014 | 2,508 | 2,202 | 2,000
Stdev | 65,867 | 4,903 | 1,647 | 1,142 | 631 | 0
Min | 5,053 | 2,000 | 2,000 | 2,000 | 2,000 | 2,000
Max | 449,739 | 48,845 | 6,978 | 5,655 | 4,236 | 2,000

So going from 2->6 would really help. Although not sure Stdev is really right measure as actually want average % change on each update. Will see if I can compute that.

**Comment by sstone** [comment] 2018-07-12 09:35
This looks a lot like an error message generated by c-lightning, which was very strict when checking fee rates until recently.
There is no good solution now, and even being more lax will not eliminate the problem completely. Users who are new to bitcoin/LN feel very uncomfortable about having their funds locked (after a force-close) or their transactions unconfirmed, and users also complain when they think that we overpaid fees which is why we don't want to be too lax and accept just any fee change. Once most c-lightning nodes have upgraded it should happen less often (but it won't go away).

**Comment by sstone** [comment] 2018-09-13 15:10
This is fixed by #684,  fee rates mismatch should now be extremely uncommon.

**Closed by sstone** 2018-09-13 15:10 UTC
