### ISSUE TITLE
Channel stuck in CLOSING state without user interaction

### ISSUE THREAD

**Issue by deafboy** [ACINQ/eclair#546] opened 2018-04-05 16:03 UTC
I've opened 2 channels on April 1st. When I logged on to the machine the next day, both channels were in a CLOSING state (and still are). From what I understand by reading the log, my node and my peers node couldn't agree on the fee rate and it somehow ended in unilateral closure.

Considering that I'm the one waiting for the money to show up, it was initiated from my side. This leads to the following questions:

Why didn't eclair attempt to do a cooperative closure?
What's the default timeout for my coins to become spendable again?

Here are the relevant parts from the logfile related to one of those channels:

> [bitcoin@eclair .eclair]$ cat eclair.log | grep 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd
2018-04-01 21:34:59,706 INFO  fr.acinq.eclair.io.Peer akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e  - channel id switch: previousId=a15e94223adacbd83c9f1dac3a80bd1ad23ff68d791633cc576e00f5d2cf3c69 nextId=624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd
2018-04-01 21:35:05,010 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - **publishing funding tx** for channelId=624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd fundingTxid=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62
2018-04-01 21:35:05,212 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - committing txid=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62
2018-04-01 21:45:36,496 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - channelId=624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd was **confirmed** at blockHeight=516173 txIndex=1705
2018-04-01 22:15:47,600 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - **funding tx is deeply buried** at blockHeight=516173 txIndex=1705 shortChannelId=7e04d0006a90001
2018-04-01 22:15:53,629 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - **announcing channelId**=624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd on the network with shortId=7e04d0006a90001
2018-04-02 15:27:57,243 ERROR fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - **peer sent error: ascii='update_fee 8192 outside range 253-6310'** bin=7570646174655f6665652038313932206f7574736964652072616e6765203235332d36333130
2018-04-02 15:27:57,253 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - **tx generation success**: desc=main-delayed-output txid=704f4376fd543a2f50375dc92dd87d996cfa501ed35d3aee88d98441002ba3cf amount=367615 tx=02000000000101e423013ed912909f3a2b12073f06a74a79135fec4cf08b36151618c130a637e400000000009000000001ff9b05000000000017a91422966d24fffd3ea01dfba9ef4df941a67065cd55870347304402205244e235fbf9f3edc4fcf602300046a72f3436c3218821085bcd4cb1b5cbfb3f02207953a0d8e35a1bb6c39e3c0844e0d7de7d3d99ae04088f0e4f8aa21d8417d72b01004d6321035f290094172ef28f1178037e40a707b72634c564e3ee32849eace9f7de17c76167029000b2752102c6c8484dfb437238e5a6dfb11c9517333e032d9ce1bab9417277518a7dde95cc68ac00000000
2018-04-02 15:28:00,282 ERROR fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - **peer sent error: ascii='Unexpected message 132 for peer'** bin=556e6578706563746564206d6573736167652031333220666f722070656572
2018-04-02 15:28:01,802 ERROR fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - p**eer sent error: ascii='update_fee 8192 outside range 253-6310'** bin=7570646174655f6665652038313932206f7574736964652072616e6765203235332d36333130
2018-04-02 16:09:17,307 WARN  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - **they published their current commit in txid**=4a9f1617e3cdaa01980f389ffded10b1bedda1cb45b2c2abf2f2ad9b368a75a5
2018-04-02 16:09:17,373 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - **tx generation success: desc=claim-p2wpkh-output** txid=dacf23b9e2c34953928fe8e424cb5fd779bf420f90f045d73ab8592f60abe7cd amount=367615 tx=02000000000101a5758a369badf2f2abc2b245cba1ddbeb110edfd9f380f9801aacde317169f4a00000000000000000001ff9b05000000000017a91422966d24fffd3ea01dfba9ef4df941a67065cd5587024730440220213889801e2735ab61cc3b30e4535448135a6239307b5ba10ebc899e9f75914402207b149c72f9586f12ed6dbd116bbdee3ac203a8f2337cea53294a7f493a796402012103fc611268ebb05764d2e155a58eebc4b2a05020a38c4d7b355f5cba555ebbf35700000000
2018-04-02 16:23:09,264 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - txid=4a9f1617e3cdaa01980f389ffded10b1bedda1cb45b2c2abf2f2ad9b368a75a5 **has reached mindepth, updating closing state**
2018-04-02 17:33:52,172 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$a 0000000000000000000000000000000000000000000000000000000000000000 - **restoring channel** channelId=624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd
[bitcoin@eclair .eclair]$ 

> [bitcoin@eclair .eclair]$ cat eclair.log | grep dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62
2018-04-01 21:35:05,010 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - **publishing funding tx** for channelId=624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd fundingTxid=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62
2018-04-01 21:35:05,212 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - committing txid=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62
2018-04-01 21:45:36,496 INFO  f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - triggering WatchConfirmed(Actor[akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b#-535194918],dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62,002062e955f006d31f01d1338df03b85ab8048c89bdd5879337940d38e6a68f753aa,3,**BITCOIN_FUNDING_DEPTHOK**)
2018-04-01 22:15:47,598 INFO  f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - triggering WatchConfirmed(Actor[akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b#-535194918],dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62,002062e955f006d31f01d1338df03b85ab8048c89bdd5879337940d38e6a68f753aa,6,**BITCOIN_FUNDING_DEEPLYBURIED**)
2018-04-02 15:27:58,259 INFO  f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - triggering WatchSpentBasic(Actor[akka://default/user/$g/router#1650801151],dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62,1,002062e955f006d31f01d1338df03b85ab8048c89bdd5879337940d38e6a68f753aa,**BITCOIN_FUNDING_EXTERNAL_CHANNEL_SPENT**(7e04d0006a90001))
2018-04-02 15:27:58,259 INFO  f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - triggering WatchSpent(Actor[akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b#-535194918],dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62,1,002062e955f006d31f01d1338df03b85ab8048c89bdd5879337940d38e6a68f753aa,**BITCOIN_FUNDING_SPENT**)
2018-04-02 15:35:34,103 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-02 15:35:38,128 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-02 16:09:17,295 INFO  f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - triggering WatchSpent(Actor[akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b#-535194918],dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62,1,002062e955f006d31f01d1338df03b85ab8048c89bdd5879337940d38e6a68f753aa,**BITCOIN_FUNDING_SPENT**)
2018-04-02 16:45:50,700 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-02 17:39:50,257 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-02 17:39:50,781 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-02 17:40:42,314 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-02 18:05:49,104 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-02 18:19:51,055 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-02 20:31:57,046 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-03 05:53:17,480 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-03 13:08:16,577 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-03 16:57:28,398 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
2018-04-05 10:39:35,160 WARN  fr.acinq.eclair.router.Router akka://default/user/$g/router  - ignoring shortChannelId=7e04d0006a90001 tx=dc40f59cec1d1fb78bd19f6a5e25230946709ed8952662aaa6d312a876e14b62 (funding tx not found in utxo)
[bitcoin@eclair .eclair]$

**Comment by pm47** [comment] 2018-04-05 18:28
> Considering that I'm the one waiting for the money to show up, it was initiated from my side.

Actually no, tx `4a9f1617e3cdaa01980f389ffded10b1bedda1cb45b2c2abf2f2ad9b368a75a5` (published by the other node) won the race and got confirmed.

Can you grep your logs for tx `dacf23b9e2c34953928fe8e424cb5fd779bf420f90f045d73ab8592f60abe7cd`? This is the tx claiming your output and sending back the funds to your wallet. It seems to have been successfully created but I can't see it on the blockchain. That's the reason why eclair is stuck in `CLOSING` state: it is waiting for this tx to be confirmed. We could publish it by hand (the actual full tx is in the log you provided), but I'd like to see what happened first. At the very least, eclair should republish it when restarted.

> Why didn't eclair attempt to do a cooperative closure?

When remote node decides that fees are unacceptable, it unilaterally publishes its commitment tx. The error message is just a courtesy, by the time eclair receives it the channel is already being closed.

**Comment by deafboy** [comment] 2018-04-05 20:11
>Can you grep your logs for tx dacf23b9e2c34953928fe8e424cb5fd779bf420f90f045d73ab8592f60abe7cd? 

Yup, now the reason for tx being stuck is much more clear:

>[bitcoin@eclair .eclair]$ cat eclair.log | grep dacf23b9e2c34953928fe8e424cb5fd779bf420f90f045d73ab8592f60abe7cd
2018-04-02 16:09:17,373 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02d1856af0fc1eabd35b4033cffcf4adc201ec0c133b598bb8adb4806b2015468e/$b 624be176a812d3a6aa622695d89e70460923255e6a9fd18bb71f1dec9cf540dd - tx generation success: desc=claim-p2wpkh-output txid=dacf23b9e2c34953928fe8e424cb5fd779bf420f90f045d73ab8592f60abe7cd amount=367615 tx=02000000000101a5758a369badf2f2abc2b245cba1ddbeb110edfd9f380f9801aacde317169f4a00000000000000000001ff9b05000000000017a91422966d24fffd3ea01dfba9ef4df941a67065cd5587024730440220213889801e2735ab61cc3b30e4535448135a6239307b5ba10ebc899e9f75914402207b149c72f9586f12ed6dbd116bbdee3ac203a8f2337cea53294a7f493a796402012103fc611268ebb05764d2e155a58eebc4b2a05020a38c4d7b355f5cba555ebbf35700000000
2018-04-02 16:09:17,389 INFO  f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - publishing tx (isRetry=false): txid=dacf23b9e2c34953928fe8e424cb5fd779bf420f90f045d73ab8592f60abe7cd tx=02000000000101a5758a369badf2f2abc2b245cba1ddbeb110edfd9f380f9801aacde317169f4a00000000000000000001ff9b05000000000017a91422966d24fffd3ea01dfba9ef4df941a67065cd5587024730440220213889801e2735ab61cc3b30e4535448135a6239307b5ba10ebc899e9f75914402207b149c72f9586f12ed6dbd116bbdee3ac203a8f2337cea53294a7f493a796402012103fc611268ebb05764d2e155a58eebc4b2a05020a38c4d7b355f5cba555ebbf35700000000
2018-04-02 16:09:17,400 ERROR f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - cannot publish tx: reason=66: **min relay fee not met** (code: -26) txid=dacf23b9e2c34953928fe8e424cb5fd779bf420f90f045d73ab8592f60abe7cd tx=02000000000101a5758a369badf2f2abc2b245cba1ddbeb110edfd9f380f9801aacde317169f4a00000000000000000001ff9b05000000000017a91422966d24fffd3ea01dfba9ef4df941a67065cd5587024730440220213889801e2735ab61cc3b30e4535448135a6239307b5ba10ebc899e9f75914402207b149c72f9586f12ed6dbd116bbdee3ac203a8f2337cea53294a7f493a796402012103fc611268ebb05764d2e155a58eebc4b2a05020a38c4d7b355f5cba555ebbf35700000000
2018-04-02 17:33:52,386 INFO  f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - publishing tx (isRetry=false): txid=dacf23b9e2c34953928fe8e424cb5fd779bf420f90f045d73ab8592f60abe7cd tx=02000000000101a5758a369badf2f2abc2b245cba1ddbeb110edfd9f380f9801aacde317169f4a00000000000000000001ff9b05000000000017a91422966d24fffd3ea01dfba9ef4df941a67065cd5587024730440220213889801e2735ab61cc3b30e4535448135a6239307b5ba10ebc899e9f75914402207b149c72f9586f12ed6dbd116bbdee3ac203a8f2337cea53294a7f493a796402012103fc611268ebb05764d2e155a58eebc4b2a05020a38c4d7b355f5cba555ebbf35700000000
2018-04-02 17:33:52,805 ERROR f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - cannot publish tx: reason=66: **min relay fee not met** (code: -26) txid=dacf23b9e2c34953928fe8e424cb5fd779bf420f90f045d73ab8592f60abe7cd tx=02000000000101a5758a369badf2f2abc2b245cba1ddbeb110edfd9f380f9801aacde317169f4a00000000000000000001ff9b05000000000017a91422966d24fffd3ea01dfba9ef4df941a67065cd5587024730440220213889801e2735ab61cc3b30e4535448135a6239307b5ba10ebc899e9f75914402207b149c72f9586f12ed6dbd116bbdee3ac203a8f2337cea53294a7f493a796402012103fc611268ebb05764d2e155a58eebc4b2a05020a38c4d7b355f5cba555ebbf35700000000
[bitcoin@eclair .eclair]$ 

I'll try to push it directly to a miner.
Some indication in the gui would be nice. There's a lot going on in the logs and I simply didn't catch this.


> When remote node decides that fees are unacceptable, it unilaterally publishes its commitment tx.

Isn't this a pretty awful DoS attack vector? I could spin up a lot of nodes with insane fee policy, forcing everyone who wants to open a channel with me to immediately force close.

**Comment by pm47** [comment] 2018-04-06 12:54
Ok this is related to #530, which has been fixed in eclair beta2 (you are probably running beta1). 

If possible, please don't touch anything, we are working on a fix that will make eclair transparently get back on its feet when a tx with zero fee has already been published. Having a real example is nice for testing.

**Comment by pm47** [comment] 2018-04-06 20:39
Would you be able to build your own version of eclair based on branch [issue-546-zerofee](https://github.com/ACINQ/eclair/tree/issue-546-zerofee)?

If so, just stop your node and restart with this version, a new tx with correct fees should be published, and after a few confirmations your channel will reach `CLOSED` state.

**Comment by deafboy** [comment] 2018-04-08 12:48
> Would you be able to build your own version of eclair based on branch issue-546-zerofee?

Both transactions has been broadcasted with non-zero fee right after eclair started.

https://blockchain.info/tx/14dfc78e4f04e80cd124338c82fcbfc7a8cc2f46380d1554a2fd9ac7e6ad82b1
https://blockchain.info/tx/00a1dc15399a45c50c1614ce4b2caa825697f034ed5616bf9550a6a40d197ef5

**Comment by pm47** [comment] 2018-04-08 12:50
Cool, so I guess we can close this since issue was fixed in 0.2-beta2? And keep the branch to help people that may run into the same issue.

**Closed** 2018-04-08 12:51 UTC
