### ISSUE TITLE
when a funding TX takes a long time to confirm, channels get stuck in syncing

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#1444] opened 2020-06-03 22:44 UTC
It's not a big deal but those channels have to be "unstuck" manually via restart or `disconnect` once the funding TX is confirmed. They don't come online automatically.

In the past, those channels sometimes got stuck for good and had to be force closed. Not sure if this is still an issue though.

**Comment by t-bast** [comment] 2020-06-04 06:59
Did this happen for channels with lnd nodes?

Being stuck in syncing is completely independent of long confirmation of funding txs (at least on the eclair side). To get out of the syncing state we wait for the remote party to send a `ChannelReestablish`, I've heard reports that lnd doesn't always send them when the funding tx is not confirmed.

Can you share the logs of around the time the funding tx was confirmed? Please filter on one specific channel before sending the logs.

**Comment by viaj3ro** [comment] 2020-06-07 18:02
it happened during the last fee spike and unfortunately I'm not 100% sure anymore which channels were affected. Will prepare logs and share here as soon as I have the issue again.

**Comment by viaj3ro** [comment] 2020-06-10 22:51
found the logs for this:

https://github.com/lightningnetwork/lnd/issues/4368#issuecomment-642306746

**Comment by t-bast** [comment] 2020-06-15 12:47
Closing this issue (see https://github.com/lightningnetwork/lnd/issues/4368) for the full details.

**Comment by viaj3ro** [comment] 2021-01-28 08:39
Unfortunately I was finally able to reproduce this bug.

I have 4 channels that are stuck in syncing and can't get unstuck. They were all opened on the 7th, 8th and 9th of January 2021 with a fee of 3 sats/byte and got their first confirmation yesterday.

I opened 2 more channels at the time, one with 11 s/b and one with 7 s/b fee. The former got a confirmation within 24 hours and the latter after 10 days on January 17th. Both didn't get stuck. I might have had to manually disconnect and reconnect to actually bring them online though. (see https://github.com/lightningnetwork/lnd/issues/4368)

The 4 that are stuck are most likely going to cost me a huge amount in force closure fees and might take months until I finally get my funds back. Any ideas, how to avoid this and get them online instead? If not, this will be quite painful, hence worth figuring out what went wrong.

My first guess would be that there didn't happen a restart of eclair until January 17th when the last of the first two channels got confirmed, which might explain why it didn't get stuck even though it took 10 days until confirmation.

Is there a way to investigate further?

**Comment by t-bast** [comment] 2021-01-28 09:53
The issue there is that your channels took too long to confirm so the fundee "forgot" them.

There must be a limit after which a fundee will forget about a channel that wasn't confirmed, otherwise it's an easy DoS vector (because it costs resources to store information about a channel and check on-chain confirmations). Right now this limit is 5 days in eclair, and probably approximately the same thing in lnd. Since your channels took more than 2 weeks to confirm, your peer deleted the data stored on their side. Unfortunately that means they probably don't have their funding private keys anymore, so can't help you do a mutual close (or restore the channel).

I agree that this is not acceptable. But there must be some time limit enforced. I have an idea that could fix this, but it requires a spec change (and a code change in all implementations). Let me know if you think that would work for you, and if it does I'll start working on a spec PR and discuss it with other implementers:

- When opening a channel, you tell your peer the deadline before which you'll get it confirmed (for example, 1440 blocks from now)
- The fundee checks that deadline, and if they find it acceptable, tell you to move forward and open the channel: otherwise if they think the deadline is too long, they will tell you straight away and you'll stop the channel open flow
- Your node broadcasts the funding transaction, and uses CPFP if needed to ensure it confirms before the deadline you and your peer agreed on
- Your peer will keep the channel information on his side until the deadline is reached

That means you'll sometimes need to pay more fees than you'd like to get your funding tx confirmed through CPFP, but that gives you a guarantee that as long as you get it confirmed before the deadline, your peer will remember it.

**Comment by pm47** [comment] 2021-01-28 12:31
> The fundee checks that deadline, and if they find it acceptable, tell you to move forward and open the channel: otherwise if they think the deadline is too long, they will tell you straight away and you'll stop the channel open flow

I like this proposal

**Comment by viaj3ro** [comment] 2021-01-28 13:38
your proposal sounds good to me! I'd suggest 2016 blocks as the standard setting for latest confirmation (same as `max-to-local-delay-blocks`)

I assume you mean CPFP of the change output? Is there a way to do this already?

**Comment by t-bast** [comment] 2021-01-28 15:04
Great, I'll work on a spec PR soon then to get the discussion started.

> what is weird, is that one opening went smoothly even though it took 10 days. Would be good to know the current limits.

It seems like this funding timeout counter is refreshed (at least in eclair) when the node reboots (ie we allow 5 *more* days for the tx to confirm). Maybe that was the reason with that peer?

> I assume you mean CPFP of the change output? Is there a way to do this already?

Yes, that's what I meant. Eclair doesn't automate this for you (but we might in the future) but it's something you can do directly with `bitcoin-cli`, since this change output belongs to your bitcoin wallet. It's a bit cumbersome and manual (see https://bitcoin.stackexchange.com/questions/99677/how-would-you-create-child-pay-for-parent-in-bitcoind-cli for example) but it should work. Maybe there are tools that already exist to simplify this (I haven't looked much into the details for now).

**Comment by t-bast** [comment] 2021-01-29 08:49
Done in https://github.com/lightningnetwork/lightning-rfc/pull/839

**Comment by t-bast** [comment] 2021-03-08 08:40
The spec PR has been merged, there is now an official timeout of 2016 blocks.
If you ensure your funding tx confirms before that deadline (with a CPFP if necessary), you should now be fine.

**Closed by t-bast** 2021-03-08 08:40 UTC
