### ISSUE TITLE
Node crash during payment

### ISSUE THREAD

**Issue by engenegr** [ACINQ/eclair#1856] opened 2021-06-30 17:03 UTC
I've tried to make payment (Mainnet) from other CL node.

My Eclair just crashed meanwhile with such error log:

```
2021-06-30 16:52:31,074 ERROR f.a.e.channel.Channel n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - fatal database error
org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at fr.acinq.eclair.db.pg.PgChannelsDb.$anonfun$addOrUpdateChannel$3(PgChannelsDb.scala:97)
	at fr.acinq.eclair.db.pg.PgChannelsDb.$anonfun$addOrUpdateChannel$3$adapted(PgChannelsDb.scala:94)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.using(JdbcUtils.scala:50)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.using$(JdbcUtils.scala:46)
	at fr.acinq.eclair.db.pg.PgUtils$.using(PgUtils.scala:32)
	at fr.acinq.eclair.db.pg.PgChannelsDb.$anonfun$addOrUpdateChannel$2(PgChannelsDb.scala:94)
	at fr.acinq.eclair.db.pg.PgChannelsDb.$anonfun$addOrUpdateChannel$2$adapted(PgChannelsDb.scala:86)
	at fr.acinq.eclair.db.pg.PgUtils$PgLock$LeaseLock.$anonfun$withLock$1(PgUtils.scala:123)
	at fr.acinq.eclair.db.pg.PgUtils$.inTransactionInternal(PgUtils.scala:255)
	at fr.acinq.eclair.db.pg.PgUtils$.$anonfun$inTransaction$1(PgUtils.scala:270)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.withConnection(JdbcUtils.scala:35)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.withConnection$(JdbcUtils.scala:32)
	at fr.acinq.eclair.db.pg.PgUtils$.withConnection(PgUtils.scala:32)
	at fr.acinq.eclair.db.pg.PgUtils$.inTransaction(PgUtils.scala:269)
	at fr.acinq.eclair.db.pg.PgUtils$PgLock$LeaseLock.withLock(PgUtils.scala:122)
```

After quick node restart it did even finalized payment.

**Comment by t-bast** [comment] 2021-07-01 07:14
What version of `eclair` were you running?
It looks similar to what was fixed in https://github.com/ACINQ/eclair/pull/1790

**Comment by t-bast** [comment] 2021-07-01 07:14
(note that postgres support is still experimental at that point)

**Comment by engenegr** [comment] 2021-07-01 08:07
My version is `0.5.2-SNAPSHOT-898c17b`

**Comment by engenegr** [comment] 2021-07-01 08:08
And I just had the same crash again when receiving a payment.

```
2021-07-01 08:03:01,860 ERROR f.a.e.channel.Channel n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - fatal database error
org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
```

**Comment by t-bast** [comment] 2021-07-01 08:10
> My version is 0.5.2-SNAPSHOT-898c17b

Interesting, so you do have the commit I linked and still see that issue.
@pm47 it looks like there are still some postgres issues lurking around, do you know what could go wrong?

**Comment by pm47** [comment] 2021-07-01 08:17
Right of the bat, no. A little bit more logs about that channel before the error happens would help pinpoint the issue. Strange that we haven't reproduced that ourselves though, we have been running that code for quite some time.

**Comment by engenegr** [comment] 2021-07-01 16:00
@pm47 OK. I tried to make a payment and easily got crash.

I sent payment in 15:57

```
2021-07-01 15:54:50,261 INFO  fr.acinq.eclair.Setup - current feeratesPerKB=FeeratesPerKB(FeeratePerKB(Satoshi(5000)),FeeratePerKB(Satoshi(78861)),FeeratePerKB(Satoshi(78861)),FeeratePerKB(Satoshi(78857)),FeeratePerKB(Satoshi(71910)),FeeratePerKB(Satoshi(37893)),FeeratePerKB(Satoshi(19175)),FeeratePerKB(Satoshi(2328)),FeeratePerKB(Satoshi(1013))) feeratesPerKw=FeeratesPerKw(FeeratePerKw(Satoshi(1250)),FeeratePerKw(Satoshi(19715)),FeeratePerKw(Satoshi(19715)),FeeratePerKw(Satoshi(19714)),FeeratePerKw(Satoshi(17977)),FeeratePerKw(Satoshi(9473)),FeeratePerKw(Satoshi(4793)),FeeratePerKw(Satoshi(582)),FeeratePerKw(Satoshi(253)))
2021-07-01 15:57:21,429 INFO  f.a.eclair.Diagnostics PAY n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - IN msg=UpdateAddHtlc(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,9,200000 msat,7e897fdce563faab1ce4a4660b21eea0004c1585e68a02851d8c06e0c64f3796,CltvExpiry(689346),OnionRoutingPacket(0,ByteVector(33 bytes, 0x033c9fcdf76b5e59ada8d63dffe734127f405f1e20c652b6258c2142fd678b954d),ByteVector(1300 bytes, #1143937172),ace36e9fad6d4bb79c58d55c02c86d16c143f5df7e3657404ce50f254253171c))
2021-07-01 15:57:21,429 INFO  f.a.e.i.Peer PAY n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - IN msg=UpdateAddHtlc(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,9,200000 msat,7e897fdce563faab1ce4a4660b21eea0004c1585e68a02851d8c06e0c64f3796,CltvExpiry(689346),OnionRoutingPacket(0,ByteVector(33 bytes, 0x033c9fcdf76b5e59ada8d63dffe734127f405f1e20c652b6258c2142fd678b954d),ByteVector(1300 bytes, #1143937172),ace36e9fad6d4bb79c58d55c02c86d16c143f5df7e3657404ce50f254253171c))
2021-07-01 15:57:21,513 INFO  f.a.eclair.Diagnostics n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - IN msg=CommitSig(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,105b234e9845fb6a4ae868579e69275935ed9707e9a0a4e47d4618fa707b8bb910ee7694c5a248e752d9ca2d92129eb3c51c0dc27e2d947c3eac491a72542aa8,List())
2021-07-01 15:57:21,513 INFO  f.a.e.i.Peer n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - IN msg=CommitSig(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,105b234e9845fb6a4ae868579e69275935ed9707e9a0a4e47d4618fa707b8bb910ee7694c5a248e752d9ca2d92129eb3c51c0dc27e2d947c3eac491a72542aa8,List())
2021-07-01 15:57:21,516 INFO  f.a.e.channel.Channel n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - built local commit number=393 toLocalMsat=1299745178 toRemoteMsat=1700054822 htlc_in=9 htlc_out= feeratePerKw=FeeratePerKw(Satoshi(21674)) txid=ad742a371fe6b0e354d9399e867680ae618d8b8582e783e5ec6be0191cbc3c66 tx=020000000196f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a70000000000fcd2818002d697130000000000220020bebfcdc3f2aed9935d2e888cdf7b2d9a63fc2ec6c2486d6ebab8c61f77ca573dd6f01900000000001600144966f9ecd16de91c2faba20c99d6c047cfe4d48dabeb1920
2021-07-01 15:57:21,524 INFO  f.a.e.i.Peer n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - OUT msg=RevokeAndAck(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,PrivateKey(e59eee902da0c85d6fd5b51d1898d89e21fab5508bcead9f08ca34dfde007cbb),03f7d75065f30ad07391b18a312689e01b34c6954479d065ca9f5173ec0acdcd8f)
2021-07-01 15:57:21,524 INFO  f.a.eclair.Diagnostics n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - OUT msg=RevokeAndAck(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,PrivateKey(e59eee902da0c85d6fd5b51d1898d89e21fab5508bcead9f08ca34dfde007cbb),03f7d75065f30ad07391b18a312689e01b34c6954479d065ca9f5173ec0acdcd8f)
2021-07-01 15:57:21,527 INFO  f.a.e.channel.Channel n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - built remote commit number=393 toLocalMsat=1700054822 toRemoteMsat=1299745178 htlc_in=9 htlc_out= feeratePerKw=FeeratePerKw(Satoshi(21674)) txid=8c1ca2d23cbe408ac2e5b3500ab84a4f613b02c8aa08296c69f27c0bdf867ca2 tx=020000000196f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a70000000000fcd2818002d6971300000000001600145ad59466eaf06a9cec76e259082a8c8eba3a180bd6f019000000000022002093e8130b7dd5ad196c1f96773ceca66952bfe823bedff4508c36e34c1c26bb59abeb1920
2021-07-01 15:57:21,533 INFO  f.a.e.i.Peer n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - OUT msg=CommitSig(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,26518ed5753547fa5d2a4758fa1977e446325181e1314c025d9a95e9a0af0ba67fcd2c41e21359abc9f7fe49a8e93f74d3586a17fa57f62f2073e97cc197fec6,List())
2021-07-01 15:57:21,533 INFO  f.a.eclair.Diagnostics n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - OUT msg=CommitSig(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,26518ed5753547fa5d2a4758fa1977e446325181e1314c025d9a95e9a0af0ba67fcd2c41e21359abc9f7fe49a8e93f74d3586a17fa57f62f2073e97cc197fec6,List())
2021-07-01 15:57:21,610 INFO  f.a.eclair.Diagnostics n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - IN msg=RevokeAndAck(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,PrivateKey(43a1e2a0e7b49f2cddb47003c6c6dab58b3b7acd1d71f656050c26fc02527e52),0381e1ae1c962e33f183cea2de8d9ee70b2c43cdcf7d699d1307f2b59904e121a3)
2021-07-01 15:57:21,610 INFO  f.a.e.i.Peer n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - IN msg=RevokeAndAck(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,PrivateKey(43a1e2a0e7b49f2cddb47003c6c6dab58b3b7acd1d71f656050c26fc02527e52),0381e1ae1c962e33f183cea2de8d9ee70b2c43cdcf7d699d1307f2b59904e121a3)
2021-07-01 15:57:21,630 INFO  f.a.e.p.r.PaymentHandler PAY h:7e897fdce563faab1ce4a4660b21eea0004c1585e68a02851d8c06e0c64f3796 - received payment for amount=200000 msat totalAmount=200000 msat
2021-07-01 15:57:21,631 INFO  f.a.e.p.r.PaymentHandler PAY h:7e897fdce563faab1ce4a4660b21eea0004c1585e68a02851d8c06e0c64f3796 - received complete payment for amount=200000 msat
2021-07-01 15:57:21,631 INFO  f.a.e.p.r.PaymentHandler PAY h:7e897fdce563faab1ce4a4660b21eea0004c1585e68a02851d8c06e0c64f3796 - fulfilling payment for amount=200000 msat
2021-07-01 15:57:21,637 INFO  f.a.e.channel.Channel n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - built remote commit number=394 toLocalMsat=1700054822 toRemoteMsat=1299945178 htlc_in= htlc_out= feeratePerKw=FeeratePerKw(Satoshi(21674)) txid=3841ea90c00b995c1a3944a686a7fb6f234d97e5bf2ee73ee7361b7dc06bb5ab tx=020000000196f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a70000000000fcd28180029e981300000000001600145ad59466eaf06a9cec76e259082a8c8eba3a180bd6f0190000000000220020cd61c9310b008c10f53b17a1ca7614814a788d8cb1b39327ca3395ad67a9f859a8eb1920
2021-07-01 15:57:21,637 INFO  f.a.e.i.Peer PAY n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - OUT msg=UpdateFulfillHtlc(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,9,02c4b0ec58d7080d91c3fc6a6ef4d85721bb1b6f9452b90f2fc2d2df78204424)
2021-07-01 15:57:21,637 INFO  f.a.eclair.Diagnostics PAY n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - OUT msg=UpdateFulfillHtlc(96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7,9,02c4b0ec58d7080d91c3fc6a6ef4d85721bb1b6f9452b90f2fc2d2df78204424)
2021-07-01 15:57:21,660 ERROR f.a.e.channel.Channel n:02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff c:96f97fc3414dc324636fc08365d50fc096b2dc24acc2faf6dbda3ca49513d4a7 - fatal database error
org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at fr.acinq.eclair.db.pg.PgChannelsDb.$anonfun$addOrUpdateChannel$3(PgChannelsDb.scala:97)
	at fr.acinq.eclair.db.pg.PgChannelsDb.$anonfun$addOrUpdateChannel$3$adapted(PgChannelsDb.scala:94)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.using(JdbcUtils.scala:50)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.using$(JdbcUtils.scala:46)
	at fr.acinq.eclair.db.pg.PgUtils$.using(PgUtils.scala:32)
	at fr.acinq.eclair.db.pg.PgChannelsDb.$anonfun$addOrUpdateChannel$2(PgChannelsDb.scala:94)
	at fr.acinq.eclair.db.pg.PgChannelsDb.$anonfun$addOrUpdateChannel$2$adapted(PgChannelsDb.scala:86)
	at fr.acinq.eclair.db.pg.PgUtils$PgLock$LeaseLock.$anonfun$withLock$1(PgUtils.scala:123)
	at fr.acinq.eclair.db.pg.PgUtils$.inTransactionInternal(PgUtils.scala:255)
	at fr.acinq.eclair.db.pg.PgUtils$.$anonfun$inTransaction$1(PgUtils.scala:270)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.withConnection(JdbcUtils.scala:35)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.withConnection$(JdbcUtils.scala:32)
	at fr.acinq.eclair.db.pg.PgUtils$.withConnection(PgUtils.scala:32)
	at fr.acinq.eclair.db.pg.PgUtils$.inTransaction(PgUtils.scala:269)
	at fr.acinq.eclair.db.pg.PgUtils$PgLock$LeaseLock.withLock(PgUtils.scala:122)
```

After quick restart node did receive payment.

**Comment by engenegr** [comment] 2021-07-01 16:02
These are all logs I have currently. I could enable some debug options if you say which one.

**Closed** 2021-07-08 15:10 UTC
