### ISSUE TITLE
Can't pay invoice with Eclair, but the node can

### ISSUE THREAD

**Issue by BitBargain** [ACINQ/eclair#551] opened 2018-04-07 19:03 UTC
I connected to my own LND node using the Eclair app on Android.

When trying to pay an invoice (on mainnet.yalls.org), Eclair comes up with all sorts of routing error messages. First it was 10 different paths being unsuccessful, the last attempt came back with "no path found to destination node - origin: your node" or similar. If there was a log of the error messages on the phone I'd copy/paste them but there isn't, it was just a red screen that popped up.

Within 10 seconds I did `payinvoice` on my node (which has over 20 well funded connections, including directly to the destination path) the invoice was paid instantly.

I'm guessing it's not normal that the node I'm connected to can pay an invoice but Eclair, being connected to the exact same node can't.

I tried to reproduce the issue, this time it worked fine and the invoice was paid (even if a bit slowly).

There was another channel in a closing state at the time. Is there any chance Eclair is attempting to pay through a channel/node that has not closed yet completely? That's the only difference between then and now - it's closed by now.

**Comment by pm47** [comment] 2018-04-09 12:38
I'm closing this as duplicate of https://github.com/ACINQ/eclair-wallet/issues/18, feel free to follow progress there, thanks!

**Closed by pm47** 2018-04-09 12:38 UTC
Labels: duplicate, eclair-mobile

**Comment by pm47** [comment] 2018-04-09 12:40
> There was another channel in a closing state at the time. Is there any chance Eclair is attempting to pay through a channel/node that has not closed yet completely?

In that case eclair would have received an `UnknownChannel` error and would have cleaned up the channel from its network db.
