### ISSUE TITLE
Payment pending for hours

### ISSUE THREAD

**Issue by lightningnetworkstores** [ACINQ/eclair#552] opened 2018-04-08 12:59 UTC
I installed eclair mainnet lightning wallet for android and tried to make a payment to mainnet.y'alls.org. The payment is pending for several hours... Printscreen of payment: https://imgur.com/a/Jc0p3

I have a channel open with a well-connected node (Torguard VPN) with enough capacity: https://imgur.com/a/jUyUH

I uncapped the routing fee in the settings, and payments are still pending for a long time. 

My nodeid is: 03fe5a217a0089a339b8cdd908719c9cbb4e7ed2ee9578f9c3f194adc095ba6e38

**Comment by lightningnetworkstores** [comment] 2018-04-08 14:50
Update: Opened another channel with rompert and now the payments go through. Would be good if I got was informed that the status was "route not found" or "destination nodes not online", ...

**Comment by pm47** [comment] 2018-04-08 14:55
In that case the issue is probably not in eclair, but in some node in the route, which has gone unresponsive, or experiences issues, and never forwards the payment or sends back the acknowledgment. After a while if nothing happens, the payment will timeout.

There isn't much that we  can do from the sender's side except wait.

**Comment by lightningnetworkstores** [comment] 2018-04-08 14:57
what's the timeout period, I have a payment pending for 17 hours...

**Comment by pm47** [comment] 2018-04-08 15:03
Final node typically set it to ~10 blocks, then each node in the route adds typically 144 blocks (a day).

**Comment by lightningnetworkstores** [comment] 2018-04-08 15:05
is there a way to set this timeout to 20 minutes or even less on my side?

**Comment by pm47** [comment] 2018-04-08 15:08
No, this timeout is required by nodes in the route, it is there for security reasons. Nodes advertise what timeout they enforce. But take the current values with a grain of salt, they will probably be reduced as the network matures.

**Comment by lightningnetworkstores** [comment] 2018-04-08 15:13
ok, thanks. By the way, are you thinking about changing the minimum amount per channel to be a higher value? 1 mBTC seems a bit too much, no?

**Comment by pm47** [comment] 2018-04-09 12:32
> ok, thanks. By the way, are you thinking about changing the minimum amount per channel to be a higher value? 1 mBTC seems a bit too much, no?

I'm not sure I understand your question. I'm closing this ticket because I think the main topic has been resolved, but feel free to continue the discussion on our [gitter](https://gitter.im/ACINQ/eclair).

**Closed by pm47** 2018-04-09 12:32 UTC
