### ISSUE TITLE
Counters used to rate-limit pending open channel requests may not be updated properly

### ISSUE THREAD

**Issue by sstone** [ACINQ/eclair#2686] opened 2023-06-08 19:02 UTC
I have a node that has a single confirmed channel with an eclair node (running on master) but still get rates limited when it tries to open a new channel.

There are 2 potential (non-exclusive) explanations:

- "private" nodes that already have confirmed channels are checked against `max-total-pending-channels-private-nodes`  instead of being checked individually against ` max-pending-channels-per-peer`
- the number of pending channels for private nodes is not decremented properly when channels are announced and associated nodes become public, and remains very high and above `max-total-pending-channels-private-nodes` , which will cause open_channel requested from new nodes to be rejected

**Comment by t-bast** [comment] 2023-06-09 08:23
I see a few issues already (but may not be exhaustive):

1. We need logs in that component, at least for the restoring part
2. When we restore, we include channels that we initiated, whereas we should only look at channels for which we're not the initiator
3. In the handlers for `ReplaceChannelId` and `RemoveChannelId`, we only clean up the `pendingPrivateNodeChannels` if we didn't find the node in the `pendingPublicNodeChannels` -> that's incorrect, a `node_id` may be in both maps, so we need to clean up both in all cases
4. In `restoring`, we register to events only after we've analyzed every channel: this is potentially too late, that means we will miss events fired while we were in `restoring`: we should register to these events first, and stash the ones that fire while we're `restoring`

**Comment by remyers** [comment] 2023-06-09 08:46
Using a testnet node to the same testnet node as @sstone is testing with, I also receive a rate limit error for my first (private) channel.

I suspect there are (at least) two primary issues that need to be addressed: 
1) why does the count of pending channel opens for private nodes not decrease after all private channel open attempts should have completed?
2) why is a public node that should be tested against it's own public count of pending channel opens being tested against the private pending channel open limit (which is not decreasing as per problem 1)

I'll investigate by first trying to create some tests that can replicate the problem.

**Comment by t-bast** [comment] 2023-06-09 09:02
> 2. why is a public node that should be tested against it's own public count of pending channel opens being tested against the private pending channel open limit (which is not decreasing as per problem 1)

I think you should first challenge that claim: we're not sure yet @sstone's node is actually public. If it is a private node, it is expected that it is checked against the private pending limits.

**Comment by remyers** [comment] 2023-06-09 14:09
I can repo the issue of treating our own initiated pending channels towards the rate limit when restoring; I'll now test and confirm the fix I have works and then start a draft PR for that.

I'll then try to do the same for those other issues you found - repo bug, fix, add to draft PR.

**Comment by sstone** [comment] 2023-06-12 07:09
The node I tested with was private, sorry for the confusion (it was public and can still be found on 1ml.testnet but its last public channel was closed and new channels are private). 
But it still had confirmed channels with the eclair node that rate-limited new channel creations

=> imho this is a bug and the rate limiter should have used the same checks as for public channels (which will require some small changes as the router does not yet return starts about node's private channel)

There are still potential issues in how we count  the number of pending private channels, maybe linked to @t-bast comments:    

> 4\. n `restoring`, we register to events only after we've analyzed every channel: this is potentially too late, that means we will miss events fired while we were in `restoring`: we should register to these events first, and stash the ones that fire while we're `restoring`

**Comment by t-bast** [comment] 2023-06-12 07:22
> But it still had confirmed channels with the eclair node that rate-limited new channel creations

That is by design, I don't see a compelling reason to change it? Why would you want to treat those nodes like public ones?

**Comment by remyers** [comment] 2023-06-12 08:21
> > But it still had confirmed channels with the eclair node that rate-limited new channel creations
> 
> That is by design, I don't see a compelling reason to change it? Why would you want to treat those nodes like public ones?

I can understand the argument that a private node with a confirmed channel to our node has the same sibyl protection as a public node. They have committed funds on-chain to establish their identity. In some ways it's stronger proof because they can't reuse private channels with our node to attack other nodes.

**Comment by sstone** [comment] 2023-06-12 08:44
Ok, so with the current implementation, it is normal to rate limit private nodes with confirmed channels like any other private node. I think it would be better to treat them differently but it's debatable and would require changes in the router so should be done later (if we decide that it is worth it in the first place).
The bug that we potentially have is that the counters we use to rate limit channel openings may be wrong (see https://github.com/ACINQ/eclair/issues/2686#issuecomment-1584173355)

**Comment by t-bast** [comment] 2023-06-14 12:16
Fixed by #2687

**Closed by t-bast** 2023-06-14 12:16 UTC
