### ISSUE TITLE
OneForOneStrategy error -  requirement failed: invalid mac

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#980] opened 2019-05-05 12:06 UTC
constantly getting this error. node seems to be working fine though. 

``2019-05-05 12:47:47,931 ERROR a.a.OneForOneStrategy  - requirement failed: invalid macjava.lang.IllegalArgumentException: requirement failed: invalid mac
	at scala.Predef$.require(Predef.scala:224)
	at fr.acinq.eclair.crypto.ChaCha20Poly1305$.decrypt(ChaCha20Poly1305.scala:125)
	at fr.acinq.eclair.crypto.Noise$Chacha20Poly1305CipherFunctions$.decrypt(Noise.scala:111)
	at fr.acinq.eclair.crypto.Noise$InitializedCipherState.decryptWithAd(Noise.scala:211)
	at fr.acinq.eclair.crypto.TransportHandler$ExtendedCipherState.decryptWithAd(TransportHandler.scala:342)
	at fr.acinq.eclair.crypto.TransportHandler$Decryptor.decrypt(TransportHandler.scala:362)
	at fr.acinq.eclair.crypto.TransportHandler$$anonfun$4.applyOrElse(TransportHandler.scala:179)
	at fr.acinq.eclair.crypto.TransportHandler$$anonfun$4.applyOrElse(TransportHandler.scala:177)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:663)
	at fr.acinq.eclair.crypto.TransportHandler.processEvent(TransportHandler.scala:53)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
	at fr.acinq.eclair.crypto.TransportHandler.fr$acinq$eclair$FSMDiagnosticActorLogging$$super$aroundReceive(TransportHandler.scala:53)
	at fr.acinq.eclair.FSMDiagnosticActorLogging$class.aroundReceive(FSMDiagnosticActorLogging.scala:38)
	at fr.acinq.eclair.crypto.TransportHandler.aroundReceive(TransportHandler.scala:53)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)``

**Comment by sstone** [comment] 2019-05-06 08:29
Looks like a duplicate of #409. Did you change your node id at any time ?

**Comment by viaj3ro** [comment] 2019-05-06 12:44
yeah, I stumbled across #409 when I googled the for the issue but my node ID is still the same.

I just realized that the external IP changed apparently and advertising the correct one again solved the issue.

Now I'm wondering if that same error occurs after an IP change even if I don't announce my IP at all?

**Comment by sstone** [comment] 2019-05-07 16:18
Is it possible that you had already used this IP address with a different node id ?

**Comment by viaj3ro** [comment] 2019-05-09 13:25
nope. I only ever used the same node ID and it never changed. Pretty sure I never used that new IP before either.

**Comment by t-bast** [comment] 2019-10-11 16:41
Closing this issue as it looks resolved.

**Closed by t-bast** 2019-10-11 16:41 UTC
